import { Topic } from './types';

export const TOPICS: Topic[] = [
  {
    key: 'history', folder: '1-Indian History', emoji: '🏛️',
    en: { name: 'Indian History', desc: 'Ancient to Modern India' },
    hi: { name: 'भारतीय इतिहास', desc: 'प्राचीन से आधुनिक भारत' },
    accent: '#d97706',
    exams: ['rrb_ntpc', 'rrb_group_d', 'ssc_cgl', 'ssc_cpo', 'ssc_chsl', 'ssc_mts', 'ssc_gd', 'up_police', 'delhi_police', 'bihar_police', 'upsc_cse', 'upsc_cds', 'upsc_capf', 'nda', 'agniveer_army', 'agniveer_navy_af', 'ib_acio', 'ctet', 'kvs_nvs', 'ugc_net', 'uppsc', 'bpsc', 'rpsc_ras', 'mppsc', 'hpsc_hcs', 'ukpsc', 'upsssc_pet', 'bssc', 'rsmssb', 'mpesb_vyapam', 'up_forest_guard', 'raj_forest_guard', 'mp_forest_guard', 'jharkhand_forest_guard', 'bihar_forest_guard', 'haryana_forest_guard', 'raj_jail_prahari', 'bihar_jail_warder', 'up_jail_prahari', 'mp_jail_prahari', 'up_lekhpal', 'raj_patwari', 'mp_patwari', 'haryana_patwari', 'gram_panchayat_vdo', 'agriculture_supervisor', 'ibps_afo', 'labour_inspector', 'aissee_sainik'],
    chapters: [
      { file: '1-Indus Valley.json', en: 'Indus Valley', hi: 'सिंधु घाटी' },
      { file: '2-Buddhism & Jainism.json', en: 'Buddhism & Jainism', hi: 'बौद्ध और जैन धर्म' },
      { file: '3-Vedic & Mahajanapadas.json', en: 'Vedic & Mahajanapadas', hi: 'वैदिक और महाजनपद' },
      { file: '4-Mauryan & Gupta.json', en: 'Mauryan & Gupta', hi: 'मौर्य और गुप्त' },
      { file: '5-Prehistoric.json', en: 'Prehistoric', hi: 'प्रागैतिहासिक काल' },
      { file: '6-Mughal Empire.json', en: 'Mughal Empire', hi: 'मुगल साम्राज्य' },
      { file: '7-Delhi Sultanate.json', en: 'Delhi Sultanate', hi: 'दिल्ली सल्तनत' },
      { file: '8-Vijayanagar.json', en: 'Vijayanagar', hi: 'विजयनगर' },
      { file: '9-Bhakti & Sufi.json', en: 'Bhakti & Sufi', hi: 'भक्ति और सूफी' },
      { file: '10-Gandhian Era.json', en: 'Gandhian Era', hi: 'गांधी युग' },
      { file: '11-Revolt of 1857.json', en: 'Revolt of 1857', hi: '1857 की क्रांति' },
      { file: '12-Congress Sessions.json', en: 'Congress Sessions', hi: 'कांग्रेस अधिवेशन' },
      { file: '13-Viceroys & Acts.json', en: 'Viceroys & Acts', hi: 'वायसराय और अधिनियम' },
      { file: '14-Social Reforms.json', en: 'Social Reforms', hi: 'सामाजिक सुधार' },
      { file: '15-World Events.json', en: 'World Events', hi: 'विश्व घटनाएं' },
      { file: '16-Revolutions.json', en: 'Revolutions', hi: 'क्रांतियां' },
    ],
  },
  {
    key: 'polity', folder: '2-Indian Polity', emoji: '⚖️',
    en: { name: 'Indian Polity', desc: 'Constitution & Governance' },
    hi: { name: 'भारतीय राजव्यवस्था', desc: 'संविधान और शासन' },
    accent: '#4527a0',
    exams: ['rrb_ntpc', 'rrb_group_d', 'ssc_cgl', 'ssc_cpo', 'ssc_chsl', 'ssc_mts', 'ssc_gd', 'up_police', 'delhi_police', 'bihar_police', 'upsc_cse', 'upsc_cds', 'upsc_capf', 'nda', 'agniveer_army', 'ib_acio', 'ugc_net', 'uppsc', 'bpsc', 'rpsc_ras', 'mppsc', 'hpsc_hcs', 'ukpsc', 'upsssc_pet', 'bssc', 'rsmssb', 'mpesb_vyapam', 'raj_jail_prahari', 'up_jail_prahari', 'mp_jail_prahari', 'up_lekhpal', 'raj_patwari', 'mp_patwari', 'haryana_patwari', 'gram_panchayat_vdo', 'labour_inspector'],
    chapters: [
      { file: '1-Constitution Basics.json', en: 'Constitution Basics', hi: 'संविधान की मूल बातें' },
      { file: '2-Schedules & Sources.json', en: 'Schedules & Sources', hi: 'अनुसूचियां और स्रोत' },
      { file: '3-Fundamental Rights.json', en: 'Fundamental Rights', hi: 'मौलिक अधिकार' },
      { file: '4-DPSP & Duties.json', en: 'DPSP & Duties', hi: 'नीति निदेशक और कर्तव्य' },
      { file: '5-Amendments.json', en: 'Amendments', hi: 'संशोधन' },
      { file: '6-President & VP.json', en: 'President & VP', hi: 'राष्ट्रपति और उपराष्ट्रपति' },
      { file: '7-Parliament.json', en: 'Parliament', hi: 'संसद' },
      { file: '8-Prime Minister.json', en: 'Prime Minister', hi: 'प्रधानमंत्री' },
      { file: '9-Parliamentary Terms.json', en: 'Parliamentary Terms', hi: 'संसदीय शब्दावली' },
      { file: '10-Emergency.json', en: 'Emergency', hi: 'आपातकाल' },
      { file: '11-Governor & CM.json', en: 'Governor & CM', hi: 'राज्यपाल और मुख्यमंत्री' },
      { file: '12-State Legislature.json', en: 'State Legislature', hi: 'राज्य विधानमंडल' },
      { file: '13-Local Government.json', en: 'Local Government', hi: 'स्थानीय शासन' },
      { file: '14-Centre-State Relations.json', en: 'Centre-State Relations', hi: 'केंद्र-राज्य संबंध' },
      { file: '15-Supreme Court.json', en: 'Supreme Court', hi: 'सर्वोच्च न्यायालय' },
      { file: '16-Writs.json', en: 'Writs', hi: 'रिट' },
      { file: '17-Constitutional Bodies.json', en: 'Constitutional Bodies', hi: 'संवैधानिक निकाय' },
      { file: '18-High Courts.json', en: 'High Courts', hi: 'उच्च न्यायालय' },
    ],
  },
  {
    key: 'geography', folder: '3-Geography', emoji: '🗺️',
    en: { name: 'Geography', desc: 'India & World Geography' },
    hi: { name: 'भूगोल', desc: 'भारत और विश्व भूगोल' },
    accent: '#00838f',
    exams: ['rrb_ntpc', 'rrb_group_d', 'ssc_cgl', 'ssc_cpo', 'ssc_chsl', 'ssc_mts', 'ssc_gd', 'up_police', 'delhi_police', 'bihar_police', 'upsc_cse', 'upsc_cds', 'upsc_capf', 'nda', 'agniveer_army', 'agniveer_navy_af', 'ctet', 'ugc_net', 'uppsc', 'bpsc', 'rpsc_ras', 'mppsc', 'hpsc_hcs', 'ukpsc', 'upsssc_pet', 'bssc', 'rsmssb', 'raj_forest_guard', 'mp_forest_guard', 'jharkhand_forest_guard', 'bihar_forest_guard', 'haryana_forest_guard', 'up_forest_guard', 'raj_jail_prahari', 'bihar_jail_warder', 'up_jail_prahari', 'mp_jail_prahari', 'up_lekhpal', 'raj_patwari', 'mp_patwari', 'haryana_patwari', 'gram_panchayat_vdo', 'agriculture_supervisor', 'ibps_afo', 'labour_inspector', 'aissee_sainik'],
    chapters: [
      { file: '1-Solar System.json', en: 'Solar System', hi: 'सौर मंडल' },
      { file: '2-Earth Structure.json', en: 'Earth Structure', hi: 'पृथ्वी की संरचना' },
      { file: '3-Atmosphere & Weather.json', en: 'Atmosphere & Weather', hi: 'वायुमंडल और मौसम' },
      { file: '4-Oceans & Currents.json', en: 'Oceans & Currents', hi: 'महासागर और धाराएं' },
      { file: '5-Rocks & Minerals.json', en: 'Rocks & Minerals', hi: 'चट्टानें और खनिज' },
      { file: '6-Plate Tectonics.json', en: 'Plate Tectonics', hi: 'प्लेट विवर्तनिकी' },
      { file: '7-Landforms.json', en: 'Landforms', hi: 'भू-आकृतियां' },
      { file: '8-Rivers of India.json', en: 'Rivers of India', hi: 'भारत की नदियां' },
      { file: '9-Census 2011.json', en: 'Census 2011', hi: 'जनगणना 2011' },
      { file: '10-Physiographic Divisions.json', en: 'Physiographic Divisions', hi: 'भौतिक विभाजन' },
      { file: '11-Agriculture.json', en: 'Agriculture', hi: 'कृषि' },
      { file: '12-Climate & Monsoon.json', en: 'Climate & Monsoon', hi: 'जलवायु और मानसून' },
      { file: '13-Soils of India.json', en: 'Soils of India', hi: 'भारत की मिट्टी' },
      { file: '14-Natural Vegetation.json', en: 'Natural Vegetation', hi: 'प्राकृतिक वनस्पति' },
      { file: '15-India Map Basics.json', en: 'India Map Basics', hi: 'भारत का मानचित्र' },
      { file: '16-Transport & Comm.json', en: 'Transport & Communication', hi: 'परिवहन और संचार' },
      { file: '17-Major Minerals.json', en: 'Major Minerals', hi: 'प्रमुख खनिज' },
      { file: '18-Power Resources.json', en: 'Power Resources', hi: 'ऊर्जा संसाधन' },
      { file: '19-Major Industries.json', en: 'Major Industries', hi: 'प्रमुख उद्योग' },
      { file: '20-Continents & Oceans.json', en: 'Continents & Oceans', hi: 'महाद्वीप और महासागर' },
      { file: '21-Straits & Canals.json', en: 'Straits & Canals', hi: 'जलडमरूमध्य और नहरें' },
      { file: '22-Deserts & Grasslands.json', en: 'Deserts & Grasslands', hi: 'रेगिस्तान और घास के मैदान' },
      { file: '23-Mountains & Plateaus.json', en: 'Mountains & Plateaus', hi: 'पर्वत और पठार' },
      { file: '24-National Parks.json', en: 'National Parks', hi: 'राष्ट्रीय उद्यान' },
      { file: '25-Pollution & Protocols.json', en: 'Pollution & Protocols', hi: 'प्रदूषण और प्रोटोकॉल' },
      { file: '26-Biosphere Reserves.json', en: 'Biosphere Reserves', hi: 'जैवमंडल रिजर्व' },
      { file: '27-Ecology Basics.json', en: 'Ecology Basics', hi: 'पारिस्थितिकी की मूल बातें' },
      { file: '28-Map based GK.json', en: 'Map Based GK', hi: 'मानचित्र आधारित GK' },
      { file: '29-Neighbors.json', en: 'Neighbors', hi: 'पड़ोसी देश' },
    ],
  },
  {
    key: 'economics', folder: '4-Economics', emoji: '📉',
    en: { name: 'Economics', desc: 'Budget, Plans & Policy' },
    hi: { name: 'अर्थव्यवस्था', desc: 'बजट, योजनाएं और नीति' },
    accent: '#ad1457',
    exams: ['rrb_ntpc', 'rrb_group_d', 'ssc_cgl', 'ssc_cpo', 'ssc_chsl', 'ssc_mts', 'ssc_gd', 'up_police', 'delhi_police', 'bihar_police', 'upsc_cse', 'upsc_cds', 'upsc_capf', 'nda', 'agniveer_army', 'agniveer_navy_af', 'ugc_net', 'uppsc', 'bpsc', 'rpsc_ras', 'mppsc', 'hpsc_hcs', 'ukpsc', 'upsssc_pet', 'bssc', 'rsmssb', 'mpesb_vyapam', 'up_lekhpal', 'raj_patwari', 'mp_patwari', 'haryana_patwari', 'gram_panchayat_vdo', 'agriculture_supervisor', 'fci_manager', 'ibps_afo', 'epfo_ssa_eo', 'labour_inspector'],
    chapters: [
      { file: '1-Five Year Plans.json', en: 'Five Year Plans', hi: 'पंचवर्षीय योजनाएं' },
      { file: '2-NITI Aayog.json', en: 'NITI Aayog', hi: 'नीति आयोग' },
      { file: '3-Committees.json', en: 'Committees', hi: 'समितियां' },
      { file: '4-RBI & Policy.json', en: 'RBI & Policy', hi: 'RBI और नीति' },
      { file: '5-Money Market.json', en: 'Money Market', hi: 'मुद्रा बाजार' },
      { file: '6-Banking Terms.json', en: 'Banking Terms', hi: 'बैंकिंग शब्दावली' },
      { file: '7-National Income.json', en: 'National Income', hi: 'राष्ट्रीय आय' },
      { file: '8-Inflation.json', en: 'Inflation', hi: 'मुद्रास्फीति' },
      { file: '9-Budget Basics.json', en: 'Budget Basics', hi: 'बजट की मूल बातें' },
      { file: '10-GST & Tax.json', en: 'GST & Tax', hi: 'GST और कर' },
      { file: '11-Census 2011.json', en: 'Census 2011', hi: 'जनगणना 2011' },
      { file: '12-Market Types.json', en: 'Market Types', hi: 'बाजार के प्रकार' },
      { file: '13-Demand & Supply.json', en: 'Demand & Supply', hi: 'मांग और पूर्ति' },
      { file: '14-Economic Curves.json', en: 'Economic Curves', hi: 'आर्थिक वक्र' },
    ],
  },
  {
    key: 'banking', folder: '5-Banking', emoji: '🏦',
    en: { name: 'Banking', desc: 'RBI, Banks & Finance' },
    hi: { name: 'बैंकिंग', desc: 'RBI, बैंक और वित्त' },
    accent: '#1565c0',
    exams: ['rrb_ntpc', 'ssc_cgl', 'ssc_chsl', 'ssc_cpo', 'uppsc', 'ibps_afo'],
    chapters: [
      { file: '1-History of Banking.json', en: 'History of Banking', hi: 'बैंकिंग का इतिहास' },
      { file: '2-Nationalization.json', en: 'Nationalization', hi: 'राष्ट्रीयकरण' },
      { file: '3-Bank Mergers.json', en: 'Bank Mergers', hi: 'बैंक विलय' },
      { file: '4-RBI Functions.json', en: 'RBI Functions', hi: 'RBI के कार्य' },
      { file: '5-Monetary Policy.json', en: 'Monetary Policy', hi: 'मौद्रिक नीति' },
      { file: '6-Subsidiaries.json', en: 'Subsidiaries', hi: 'सहायक कंपनियां' },
      { file: '7-Payment & Small Banks.json', en: 'Payment & Small Banks', hi: 'पेमेंट और स्मॉल बैंक' },
      { file: '8-RRBs & Co-operative.json', en: 'RRBs & Co-operative', hi: 'RRB और सहकारी बैंक' },
      { file: '9-NBFCs.json', en: 'NBFCs', hi: 'NBFC' },
      { file: '10-Digital Payments.json', en: 'Digital Payments', hi: 'डिजिटल भुगतान' },
      { file: '11-NPCI Products.json', en: 'NPCI Products', hi: 'NPCI उत्पाद' },
      { file: '12-ATM Types.json', en: 'ATM Types', hi: 'ATM के प्रकार' },
      { file: '13-NPA & SARFAESI.json', en: 'NPA & SARFAESI', hi: 'NPA और SARFAESI' },
      { file: '14-Basel Norms.json', en: 'Basel Norms', hi: 'बेसल मानदंड' },
      { file: '15-Money Market.json', en: 'Money Market', hi: 'मुद्रा बाजार' },
    ],
  },
  {
    key: 'physics', folder: '6-Physics', emoji: '🔭',
    en: { name: 'Physics', desc: 'Units, Light, Sound & More' },
    hi: { name: 'भौतिकी', desc: 'इकाइयां, प्रकाश, ध्वनि' },
    accent: '#00897b',
    exams: ['rrb_ntpc', 'rrb_group_d', 'ssc_cgl', 'ssc_cpo', 'ssc_chsl', 'ssc_mts', 'ssc_gd', 'up_police', 'delhi_police', 'bihar_police', 'rrb_alp', 'nda', 'agniveer_army', 'agniveer_navy_af', 'ctet', 'kvs_nvs', 'ugc_net', 'uptet', 'stet_bihar', 'super_tet', 'reet', 'upsssc_pet', 'bssc', 'rsmssb', 'mpesb_vyapam', 'up_forest_guard', 'raj_jail_prahari', 'bihar_jail_warder', 'up_jail_prahari', 'mp_jail_prahari', 'aissee_sainik'],
    chapters: [
      { file: '1-Physics Basics.json', en: 'Physics Basics', hi: 'भौतिकी की मूल बातें' },
      { file: '2-SI Units.json', en: 'SI Units', hi: 'SI इकाइयां' },
      { file: '3-Scientific Instruments.json', en: 'Scientific Instruments', hi: 'वैज्ञानिक उपकरण' },
      { file: '4-Inventions.json', en: 'Inventions', hi: 'आविष्कार' },
      { file: '5-Motion.json', en: 'Motion', hi: 'गति' },
      { file: '6-Newton\'s Laws.json', en: "Newton's Laws", hi: 'न्यूटन के नियम' },
      { file: '7-Friction.json', en: 'Friction', hi: 'घर्षण' },
      { file: '8-Work & Energy.json', en: 'Work & Energy', hi: 'कार्य और ऊर्जा' },
      { file: '9-Gravitation.json', en: 'Gravitation', hi: 'गुरुत्वाकर्षण' },
      { file: '10-Temperature.json', en: 'Temperature', hi: 'तापमान' },
      { file: '11-Heat Transfer.json', en: 'Heat Transfer', hi: 'ऊष्मा स्थानांतरण' },
      { file: '12-Expansion.json', en: 'Expansion', hi: 'प्रसार' },
      { file: '12-Thermodynamics.json', en: 'Thermodynamics', hi: 'ऊष्मागतिकी' },
      { file: '13-Reflection.json', en: 'Reflection', hi: 'परावर्तन' },
      { file: '14-Refraction.json', en: 'Refraction', hi: 'अपवर्तन' },
      { file: '15-Human Eye.json', en: 'Human Eye', hi: 'मानव नेत्र' },
      { file: '16-Sound.json', en: 'Sound', hi: 'ध्वनि' },
      { file: '17-Waves Basics.json', en: 'Waves Basics', hi: 'तरंगों की मूल बातें' },
      { file: '18-Electricity.json', en: 'Electricity', hi: 'विद्युत' },
      { file: '19-Circuits.json', en: 'Circuits', hi: 'परिपथ' },
      { file: '20-Magnetism.json', en: 'Magnetism', hi: 'चुंबकत्व' },
      { file: '21-EM Wave.json', en: 'EM Waves', hi: 'विद्युत चुंबकीय तरंगें' },
      { file: '22-Nuclear & Radioactivity.json', en: 'Nuclear & Radioactivity', hi: 'नाभिकीय और रेडियोधर्मिता' },
    ],
  },
  {
    key: 'chemistry', folder: '7-Chemistry', emoji: '⚗️',
    en: { name: 'Chemistry', desc: 'Elements, Reactions & More' },
    hi: { name: 'रसायन शास्त्र', desc: 'तत्व, अभिक्रियाएं और अधिक' },
    accent: '#d81b60',
    exams: ['rrb_ntpc', 'rrb_group_d', 'ssc_cgl', 'ssc_cpo', 'ssc_chsl', 'ssc_mts', 'ssc_gd', 'up_police', 'delhi_police', 'bihar_police', 'rrb_alp', 'nda', 'agniveer_army', 'agniveer_navy_af', 'ctet', 'kvs_nvs', 'uptet', 'stet_bihar', 'super_tet', 'reet', 'up_forest_guard', 'bihar_jail_warder', 'aissee_sainik'],
    chapters: [
      { file: '1-Atomic Structure.json', en: 'Atomic Structure', hi: 'परमाणु संरचना' },
      { file: '2-Mole Concept.json', en: 'Mole Concept', hi: 'मोल संकल्पना' },
      { file: '3-Matter & Mixtures.json', en: 'Matter & Mixtures', hi: 'पदार्थ और मिश्रण' },
      { file: '4-Chemical Reactions.json', en: 'Chemical Reactions', hi: 'रासायनिक अभिक्रियाएं' },
      { file: '5-Periodic Table.json', en: 'Periodic Table', hi: 'आवर्त सारणी' },
      { file: '6-Periodic Trends.json', en: 'Periodic Trends', hi: 'आवर्ती प्रवृत्तियां' },
      { file: '7-Chemical Bonding.json', en: 'Chemical Bonding', hi: 'रासायनिक बंधन' },
      { file: '8-Acids & Bases.json', en: 'Acids & Bases', hi: 'अम्ल और क्षार' },
      { file: '9-Common Names.json', en: 'Common Names', hi: 'सामान्य नाम' },
      { file: '10-Important Salts.json', en: 'Important Salts', hi: 'महत्वपूर्ण लवण' },
      { file: '11-Organic Basics.json', en: 'Organic Basics', hi: 'कार्बनिक रसायन' },
      { file: '12-Man-Made Materials.json', en: 'Man-Made Materials', hi: 'मानव निर्मित सामग्री' },
      { file: '13-Everyday Chem.json', en: 'Everyday Chemistry', hi: 'रोजमर्रा का रसायन' },
      { file: '14-Metals & Ores.json', en: 'Metals & Ores', hi: 'धातुएं और अयस्क' },
      { file: '15-Alloys.json', en: 'Alloys', hi: 'मिश्र धातुएं' },
      { file: '16-Industrial Chem.json', en: 'Industrial Chemistry', hi: 'औद्योगिक रसायन' },
    ],
  },
  {
    key: 'biology', folder: '8-Biology', emoji: '🧬',
    en: { name: 'Biology', desc: 'Human Body, Plants & Diseases' },
    hi: { name: 'जीवविज्ञान', desc: 'मानव शरीर, पौधे और रोग' },
    accent: '#2e7d32',
    exams: ['rrb_ntpc', 'rrb_group_d', 'ssc_cgl', 'ssc_cpo', 'ssc_chsl', 'ssc_mts', 'ssc_gd', 'up_police', 'delhi_police', 'bihar_police', 'rrb_alp', 'nda', 'agniveer_army', 'agniveer_navy_af', 'ctet', 'kvs_nvs', 'uptet', 'stet_bihar', 'super_tet', 'reet', 'up_forest_guard', 'bihar_jail_warder', 'aissee_sainik'],
    chapters: [
      { file: '1-Cell Structure.json', en: 'Cell Structure', hi: 'कोशिका संरचना' },
      { file: '2-Tissues.json', en: 'Tissues', hi: 'ऊतक' },
      { file: '3-Animal Kingdom.json', en: 'Animal Kingdom', hi: 'जंतु जगत' },
      { file: '4-Biology Basics.json', en: 'Biology Basics', hi: 'जीवविज्ञान की मूल बातें' },
      { file: '5-Digestive System.json', en: 'Digestive System', hi: 'पाचन तंत्र' },
      { file: '6-Circulatory System.json', en: 'Circulatory System', hi: 'परिसंचरण तंत्र' },
      { file: '7-Respiratory System.json', en: 'Respiratory System', hi: 'श्वसन तंत्र' },
      { file: '8-Excretory System.json', en: 'Excretory System', hi: 'उत्सर्जन तंत्र' },
      { file: '9-Nervous System.json', en: 'Nervous System', hi: 'तंत्रिका तंत्र' },
      { file: '10-Endocrine System.json', en: 'Endocrine System', hi: 'अंतःस्रावी तंत्र' },
      { file: '11-Skeletal System.json', en: 'Skeletal System', hi: 'कंकाल तंत्र' },
      { file: '12-Reproduction.json', en: 'Reproduction', hi: 'प्रजनन' },
      { file: '13-Vitamins & Minerals.json', en: 'Vitamins & Minerals', hi: 'विटामिन और खनिज' },
      { file: '14-Human Diseases.json', en: 'Human Diseases', hi: 'मानव रोग' },
      { file: '15-Nutrition Basics.json', en: 'Nutrition Basics', hi: 'पोषण की मूल बातें' },
      { file: '16-Immunity.json', en: 'Immunity', hi: 'रोग प्रतिरोधक क्षमता' },
      { file: '17-Plant Classification.json', en: 'Plant Classification', hi: 'पौधों का वर्गीकरण' },
      { file: '18-Plant Morphology.json', en: 'Plant Morphology', hi: 'पादप आकारिकी' },
      { file: '19-Photosynthesis.json', en: 'Photosynthesis', hi: 'प्रकाश संश्लेषण' },
      { file: '20-Plant Hormones.json', en: 'Plant Hormones', hi: 'पादप हार्मोन' },
      { file: '21-Genetics.json', en: 'Genetics', hi: 'आनुवंशिकी' },
    ],
  },
  {
    key: 'sports', folder: '9-Sports', emoji: '🏅',
    en: { name: 'Sports', desc: 'Olympics, Cricket, Awards' },
    hi: { name: 'खेल', desc: 'ओलंपिक, क्रिकेट, पुरस्कार' },
    accent: '#43a047',
    exams: ['rrb_ntpc', 'rrb_group_d', 'rrb_alp', 'rpf_constable', 'ssc_cgl', 'ssc_cpo', 'ssc_chsl', 'ssc_mts', 'ssc_gd', 'up_police', 'delhi_police', 'bihar_police', 'haryana_police', 'rajasthan_police', 'mp_police', 'upsc_cse', 'upsc_cds', 'upsc_capf', 'nda', 'agniveer_army', 'agniveer_navy_af', 'ib_acio', 'ctet', 'kvs_nvs', 'ugc_net', 'uptet', 'stet_bihar', 'super_tet', 'reet', 'uppsc', 'bpsc', 'rpsc_ras', 'mppsc', 'hpsc_hcs', 'ukpsc', 'upsssc_pet', 'bssc', 'rsmssb', 'mpesb_vyapam', 'up_forest_guard', 'raj_forest_guard', 'mp_forest_guard', 'jharkhand_forest_guard', 'bihar_forest_guard', 'haryana_forest_guard', 'raj_jail_prahari', 'bihar_jail_warder', 'up_jail_prahari', 'mp_jail_prahari', 'up_lekhpal', 'raj_patwari', 'mp_patwari', 'haryana_patwari', 'gram_panchayat_vdo', 'agriculture_supervisor', 'fci_manager', 'ibps_afo', 'epfo_ssa_eo', 'labour_inspector', 'aissee_sainik'],
    chapters: [
      { file: '1-Sports Terms.json', en: 'Sports Terms', hi: 'खेल शब्दावली' },
      { file: '2-Team Sizes.json', en: 'Team Sizes', hi: 'टीम का आकार' },
      { file: '3-Courts & Fields.json', en: 'Courts & Fields', hi: 'कोर्ट और मैदान' },
      { file: '4-Sports Basics.json', en: 'Sports Basics', hi: 'खेल की मूल बातें' },
      { file: '5-Cricket Cups.json', en: 'Cricket Cups', hi: 'क्रिकेट कप' },
      { file: '6-Football Cups.json', en: 'Football Cups', hi: 'फुटबॉल कप' },
      { file: '7-Hockey Cups.json', en: 'Hockey Cups', hi: 'हॉकी कप' },
      { file: '8-Grand Slams.json', en: 'Grand Slams', hi: 'ग्रैंड स्लैम' },
      { file: '9-Other Trophies.json', en: 'Other Trophies', hi: 'अन्य ट्रॉफी' },
      { file: '10-Indian Athletes.json', en: 'Indian Athletes', hi: 'भारतीय खिलाड़ी' },
      { file: '11-Sports Books.json', en: 'Sports Books', hi: 'खेल पुस्तकें' },
      { file: '12-Indian Firsts.json', en: 'Indian Firsts', hi: 'भारत में पहली बार' },
      { file: '13-National Sports.json', en: 'National Sports', hi: 'राष्ट्रीय खेल' },
      { file: '14-Indian Awards.json', en: 'Indian Awards', hi: 'भारतीय पुरस्कार' },
      { file: '15-Sports Legends.json', en: 'Sports Legends', hi: 'खेल किंवदंतियां' },
      { file: '16-Organizations.json', en: 'Organizations', hi: 'संगठन' },
      { file: '17-World Firsts.json', en: 'World Firsts', hi: 'विश्व में पहली बार' },
      { file: '18-Olympics History.json', en: 'Olympics History', hi: 'ओलंपिक इतिहास' },
      { file: '19-Asian & CW Games.json', en: 'Asian & CW Games', hi: 'एशियाई और CW खेल' },
      { file: '20-World Cups.json', en: 'World Cups', hi: 'विश्व कप' },
    ],
  },
  {
    key: 'abbreviations', folder: '10-Abbreviations', emoji: '🔤',
    en: { name: 'Abbreviations', desc: 'Full Forms (USB, GDP, etc.)' },
    hi: { name: 'संक्षेपाक्षर', desc: 'पूर्ण रूप (USB, GDP आदि)' },
    accent: '#37474f',
    exams: ['rrb_ntpc', 'rrb_group_d', 'ssc_cgl', 'ssc_cpo', 'ssc_chsl', 'ssc_mts'],
    chapters: [
      { file: '1-Computer Terms.json', en: 'Computer Terms', hi: 'कंप्यूटर शब्द' },
      { file: '2-Internet & Web.json', en: 'Internet & Web', hi: 'इंटरनेट और वेब' },
      { file: '3-File Formats.json', en: 'File Formats', hi: 'फाइल फॉर्मेट' },
      { file: '4-Banking Terms.json', en: 'Banking Terms', hi: 'बैंकिंग शब्द' },
      { file: '5-Economy & Tax.json', en: 'Economy & Tax', hi: 'अर्थव्यवस्था और कर' },
      { file: '6-Financial Bodies.json', en: 'Financial Bodies', hi: 'वित्तीय निकाय' },
      { file: '7-Govt Schemes.json', en: 'Govt Schemes', hi: 'सरकारी योजनाएं' },
      { file: '8-National Bodies-GK.json', en: 'National Bodies', hi: 'राष्ट्रीय निकाय' },
      { file: '10-Education & Research.json', en: 'Education & Research', hi: 'शिक्षा और अनुसंधान' },
      { file: '11-Exam Bodies.json', en: 'Exam Bodies', hi: 'परीक्षा निकाय' },
      { file: '12-Defence & Police.json', en: 'Defence & Police', hi: 'रक्षा और पुलिस' },
      { file: '13-Space & Science.json', en: 'Space & Science', hi: 'अंतरिक्ष और विज्ञान' },
      { file: '14-Legal Terms.json', en: 'Legal Terms', hi: 'कानूनी शब्द' },
      { file: '15-UN & Agencies.json', en: 'UN & Agencies', hi: 'UN और एजेंसियां' },
      { file: '16-Global Groups.json', en: 'Global Groups', hi: 'वैश्विक समूह' },
      { file: '17-Global Finance.json', en: 'Global Finance', hi: 'वैश्विक वित्त' },
    ],
  },
  {
    key: 'arts', folder: '11-Art and Culture', emoji: '🎭',
    en: { name: 'Arts & Culture', desc: 'Dances, Festivals, Temples' },
    hi: { name: 'कला और संस्कृति', desc: 'नृत्य, त्यौहार, मंदिर' },
    accent: '#6d4c41',
    exams: ['rrb_ntpc', 'ssc_cgl', 'ssc_cpo', 'up_police', 'delhi_police', 'bihar_police', 'upsc_cse', 'kvs_nvs', 'uppsc', 'bpsc', 'rpsc_ras', 'mppsc', 'hpsc_hcs', 'ukpsc', 'upsssc_pet', 'ctet'],
    chapters: [
      { file: '1-Classical Dances.json', en: 'Classical Dances', hi: 'शास्त्रीय नृत्य' },
      { file: '2-Folk Dances.json', en: 'Folk Dances', hi: 'लोक नृत्य' },
      { file: '3-Instruments & Artists.json', en: 'Instruments & Artists', hi: 'वाद्य यंत्र और कलाकार' },
      { file: '4-Indian Music.json', en: 'Indian Music', hi: 'भारतीय संगीत' },
      { file: '5-Martial Arts.json', en: 'Martial Arts', hi: 'मार्शल आर्ट' },
      { file: '6-Fairs & Festivals.json', en: 'Fairs & Festivals', hi: 'मेले और त्यौहार' },
      { file: '7-Tribes & Attire.json', en: 'Tribes & Attire', hi: 'जनजातियां और वेशभूषा' },
      { file: '8-Intangible Heritage.json', en: 'Intangible Heritage', hi: 'अमूर्त विरासत' },
      { file: '9-Temple Architecture.json', en: 'Temple Architecture', hi: 'मंदिर स्थापत्य' },
      { file: '10-Paintings.json', en: 'Paintings', hi: 'चित्रकला' },
      { file: '11-Caves & Stupas.json', en: 'Caves & Stupas', hi: 'गुफाएं और स्तूप' },
      { file: '12-Indo-Islamic Arch.json', en: 'Indo-Islamic Architecture', hi: 'भारत-इस्लामी स्थापत्य' },
      { file: '13-Ancient Books.json', en: 'Ancient Books', hi: 'प्राचीन पुस्तकें' },
      { file: '14-Modern Literature.json', en: 'Modern Literature', hi: 'आधुनिक साहित्य' },
      { file: '15-Languages.json', en: 'Languages', hi: 'भाषाएं' },
      { file: '16-UNESCO Sites.json', en: 'UNESCO Sites', hi: 'UNESCO स्थल' },
      { file: '17-Cultural Institutions.json', en: 'Cultural Institutions', hi: 'सांस्कृतिक संस्थाएं' },
      { file: '18-Religions & Philo.json', en: 'Religions & Philosophy', hi: 'धर्म और दर्शन' },
    ],
  },
  {
    key: 'inventions', folder: '12-Inventions', emoji: '💡',
    en: { name: 'Inventions', desc: 'Discoveries & Scientists' },
    hi: { name: 'आविष्कार', desc: 'खोजें और वैज्ञानिक' },
    accent: '#ff8f00',
    exams: [],
    chapters: [
      { file: '1-Everyday Inventions.json', en: 'Everyday Inventions', hi: 'रोजमर्रा के आविष्कार' },
      { file: '2-Physics Inventions.json', en: 'Physics Inventions', hi: 'भौतिकी के आविष्कार' },
      { file: '3-Chemistry Discoveries.json', en: 'Chemistry Discoveries', hi: 'रसायन की खोजें' },
      { file: '4-Industrial Era.json', en: 'Industrial Era', hi: 'औद्योगिक युग' },
      { file: '5-Medical Inventions.json', en: 'Medical Inventions', hi: 'चिकित्सा आविष्कार' },
      { file: '6-Biology Discoveries.json', en: 'Biology Discoveries', hi: 'जीवविज्ञान की खोजें' },
      { file: '7-Computer Pioneers.json', en: 'Computer Pioneers', hi: 'कंप्यूटर अग्रदूत' },
      { file: '8-Modern Tech.json', en: 'Modern Tech', hi: 'आधुनिक तकनीक' },
      { file: '9-Modern Scientists.json', en: 'Modern Scientists', hi: 'आधुनिक वैज्ञानिक' },
      { file: '10-Ancient Scientists.json', en: 'Ancient Scientists', hi: 'प्राचीन वैज्ञानिक' },
      { file: '11-Fathers of Science.json', en: 'Fathers of Science', hi: 'विज्ञान के जनक' },
      { file: '12-Fathers of Arts.json', en: 'Fathers of Arts', hi: 'कला के जनक' },
      { file: '13-Ancient & Medieval.json', en: 'Ancient & Medieval', hi: 'प्राचीन और मध्यकालीन' },
    ],
  },
  {
    key: 'famous_people', folder: '13-Famous People', emoji: '👤',
    en: { name: 'Famous People', desc: 'Authors, Leaders, Icons' },
    hi: { name: 'प्रसिद्ध व्यक्ति', desc: 'लेखक, नेता, आइकन' },
    accent: '#546e7a',
    exams: [],
    chapters: [
      { file: '1-Modern Authors.json', en: 'Modern Authors', hi: 'आधुनिक लेखक' },
      { file: '2-Poets & Philosophers.json', en: 'Poets & Philosophers', hi: 'कवि और दार्शनिक' },
      { file: '3-Autobiographies.json', en: 'Autobiographies', hi: 'आत्मकथाएं' },
      { file: '4-Cultural Icons.json', en: 'Cultural Icons', hi: 'सांस्कृतिक आइकन' },
      { file: '5-Cinema Legends.json', en: 'Cinema Legends', hi: 'सिनेमा किंवदंतियां' },
      { file: '6-Artists & Painters.json', en: 'Artists & Painters', hi: 'कलाकार और चित्रकार' },
      { file: '7-Nicknames & Titles.json', en: 'Nicknames & Titles', hi: 'उपनाम और उपाधियां' },
      { file: '8-Slogans & Quotes.json', en: 'Slogans & Quotes', hi: 'नारे और उद्धरण' },
      { file: '9-First in India (Men).json', en: 'First in India (Men)', hi: 'भारत में प्रथम (पुरुष)' },
      { file: '10-First in India (Women).json', en: 'First in India (Women)', hi: 'भारत में प्रथम (महिला)' },
      { file: '11-Social Reformers.json', en: 'Social Reformers', hi: 'समाज सुधारक' },
      { file: '12-Scientific Minds.json', en: 'Scientific Minds', hi: 'वैज्ञानिक दिमाग' },
      { file: '13-Nobel Laureates.json', en: 'Nobel Laureates', hi: 'नोबेल पुरस्कार विजेता' },
      { file: '14-World Personalities.json', en: 'World Personalities', hi: 'विश्व हस्तियां' },
      { file: '15-Explorers.json', en: 'Explorers', hi: 'अन्वेषक' },
    ],
  },
  {
    key: 'days_years', folder: '14-Days and Years', emoji: '📅',
    en: { name: 'Days & Years', desc: 'Important Dates & Events' },
    hi: { name: 'दिवस और वर्ष', desc: 'महत्वपूर्ण तिथियां और घटनाएं' },
    accent: '#7b1fa2',
    exams: [],
    chapters: [
      { file: '1-January – March.json', en: 'January – March', hi: 'जनवरी – मार्च' },
      { file: '2-April – June.json', en: 'April – June', hi: 'अप्रैल – जून' },
      { file: '3-July – September.json', en: 'July – September', hi: 'जुलाई – सितंबर' },
      { file: '4-October – December.json', en: 'October – December', hi: 'अक्टूबर – दिसंबर' },
      { file: '5-Environment Days.json', en: 'Environment Days', hi: 'पर्यावरण दिवस' },
      { file: '6-Health & Disease.json', en: 'Health & Disease', hi: 'स्वास्थ्य और रोग' },
      { file: '7-Important Battles.json', en: 'Important Battles', hi: 'महत्वपूर्ण युद्ध' },
      { file: '8-Modern History Years.json', en: 'Modern History Years', hi: 'आधुनिक इतिहास के वर्ष' },
      { file: '9-Governor Generals.json', en: 'Governor Generals', hi: 'गवर्नर जनरल' },
      { file: '10-World Events (Brief).json', en: 'World Events', hi: 'विश्व घटनाएं' },
      { file: '11-Financial Bodies.json', en: 'Financial Bodies', hi: 'वित्तीय निकाय' },
      { file: '12-Govt Organizations.json', en: 'Govt Organizations', hi: 'सरकारी संगठन' },
      { file: '13-Projects & Acts.json', en: 'Projects & Acts', hi: 'परियोजनाएं और अधिनियम' },
    ],
  },
  {
    key: 'books_authors', folder: '15-Books and Authors', emoji: '📖',
    en: { name: 'Books & Authors', desc: 'Famous Books & Writers' },
    hi: { name: 'पुस्तकें और लेखक', desc: 'प्रसिद्ध पुस्तकें और लेखक' },
    accent: '#558b2f',
    exams: [],
    chapters: [
      { file: '1-Indian English Authors.json', en: 'Indian English Authors', hi: 'भारतीय अंग्रेजी लेखक' },
      { file: '2-Modern HindiRegional.json', en: 'Modern Hindi/Regional', hi: 'आधुनिक हिंदी/क्षेत्रीय' },
      { file: '3-Politicians\' Books.json', en: "Politicians' Books", hi: 'राजनेताओं की पुस्तकें' },
      { file: '4-Sports Biographies.json', en: 'Sports Biographies', hi: 'खेल जीवनियां' },
      { file: '5-Leaders\' Biographies.json', en: "Leaders' Biographies", hi: 'नेताओं की जीवनियां' },
      { file: '6-Cinema & Arts Bios.json', en: 'Cinema & Arts Bios', hi: 'सिनेमा और कला जीवनियां' },
      { file: '7-Ancient & Classical.json', en: 'Ancient & Classical', hi: 'प्राचीन और शास्त्रीय' },
      { file: '8-Religious & Epics.json', en: 'Religious & Epics', hi: 'धार्मिक और महाकाव्य' },
      { file: '9-Mughal & Travellers.json', en: 'Mughal & Travellers', hi: 'मुगल और यात्री' },
      { file: '10-Booker Prize Winners.json', en: 'Booker Prize Winners', hi: 'बुकर पुरस्कार विजेता' },
      { file: '11-Jnanpith & Akademi.json', en: 'Jnanpith & Akademi', hi: 'ज्ञानपीठ और अकादमी' },
      { file: '12-Nobel in Literature.json', en: 'Nobel in Literature', hi: 'साहित्य में नोबेल' },
      { file: '13-World Classics.json', en: 'World Classics', hi: 'विश्व क्लासिक' },
      { file: '14-Famous Characters.json', en: 'Famous Characters', hi: 'प्रसिद्ध पात्र' },
    ],
  },
  {
    key: 'awards', folder: '16-Awards and Honors', emoji: '🏆',
    en: { name: 'Awards & Honors', desc: 'Nobel, Bharat Ratna & More' },
    hi: { name: 'पुरस्कार और सम्मान', desc: 'नोबेल, भारत रत्न और अधिक' },
    accent: '#f9a825',
    exams: [],
    chapters: [
      { file: '1-Bharat Ratna.json', en: 'Bharat Ratna', hi: 'भारत रत्न' },
      { file: '2-Padma Awards.json', en: 'Padma Awards', hi: 'पद्म पुरस्कार' },
      { file: '3-Gallantry.json', en: 'Gallantry Awards', hi: 'वीरता पुरस्कार' },
      { file: '4-Gandhi Peace Prize.json', en: 'Gandhi Peace Prize', hi: 'गांधी शांति पुरस्कार' },
      { file: '5-Dadasaheb Phalke.json', en: 'Dadasaheb Phalke', hi: 'दादासाहेब फालके' },
      { file: '6-National Film Awards.json', en: 'National Film Awards', hi: 'राष्ट्रीय फिल्म पुरस्कार' },
      { file: '7-Oscars & Grammys.json', en: 'Oscars & Grammys', hi: 'ऑस्कर और ग्रैमी' },
      { file: '8-Sangeet Natak Akademi.json', en: 'Sangeet Natak Akademi', hi: 'संगीत नाटक अकादमी' },
      { file: '9-Jnanpith Award.json', en: 'Jnanpith Award', hi: 'ज्ञानपीठ पुरस्कार' },
      { file: '10-Sahitya Akademi.json', en: 'Sahitya Akademi', hi: 'साहित्य अकादमी' },
      { file: '11-Saraswati.json', en: 'Saraswati Award', hi: 'सरस्वती पुरस्कार' },
      { file: '12-Major Dhyan Chand.json', en: 'Major Dhyan Chand', hi: 'मेजर ध्यानचंद' },
      { file: '13-Arjuna Award.json', en: 'Arjuna Award', hi: 'अर्जुन पुरस्कार' },
      { file: '14-Dronacharya Award.json', en: 'Dronacharya Award', hi: 'द्रोणाचार्य पुरस्कार' },
      { file: '15-Nobel Prize.json', en: 'Nobel Prize', hi: 'नोबेल पुरस्कार' },
      { file: '16-Ramon Magsaysay.json', en: 'Ramon Magsaysay', hi: 'रेमन मैग्सेसे' },
      { file: '17-Miss World.json', en: 'Miss World', hi: 'मिस वर्ल्ड' },
    ],
  },
  {
    key: 'world_org', folder: '17-World Organisations', emoji: '🌍',
    en: { name: 'World Organizations', desc: 'UN, WHO, G20 & More' },
    hi: { name: 'विश्व संगठन', desc: 'UN, WHO, G20 और अधिक' },
    accent: '#0277bd',
    exams: [],
    chapters: [
      { file: '1-UN Agencies (HQ).json', en: 'UN Agencies (HQ)', hi: 'UN एजेंसियां (मुख्यालय)' },
      { file: '2-UN Organs.json', en: 'UN Organs', hi: 'UN अंग' },
      { file: '3-Secretaries & History.json', en: 'Secretaries & History', hi: 'महासचिव और इतिहास' },
      { file: '4-World Bank & IMF.json', en: 'World Bank & IMF', hi: 'विश्व बैंक और IMF' },
      { file: '5-WTO & Trade.json', en: 'WTO & Trade', hi: 'WTO और व्यापार' },
      { file: '6-Regional Banks.json', en: 'Regional Banks', hi: 'क्षेत्रीय बैंक' },
      { file: '7-G20 & G7.json', en: 'G20 & G7', hi: 'G20 और G7' },
      { file: '8-SAARC & ASEAN.json', en: 'SAARC & ASEAN', hi: 'SAARC और ASEAN' },
      { file: '9-NATO & EU.json', en: 'NATO & EU', hi: 'NATO और EU' },
      { file: '10-SCO & BRICS.json', en: 'SCO & BRICS', hi: 'SCO और BRICS' },
      { file: '11-Global Indices.json', en: 'Global Indices', hi: 'वैश्विक सूचकांक' },
      { file: '12-Financial Reports.json', en: 'Financial Reports', hi: 'वित्तीय रिपोर्ट' },
      { file: '13-Environment Bodies.json', en: 'Environment Bodies', hi: 'पर्यावरण निकाय' },
      { file: '14-Sports & Others.json', en: 'Sports & Others', hi: 'खेल और अन्य' },
    ],
  },
  {
    key: 'famous_places', folder: '18-Famous Places', emoji: '🏰',
    en: { name: 'Famous Places', desc: 'Monuments, Temples, Sites' },
    hi: { name: 'प्रसिद्ध स्थान', desc: 'स्मारक, मंदिर, स्थल' },
    accent: '#ef6c00',
    exams: [],
    chapters: [
      { file: '1-Historical Monuments.json', en: 'Historical Monuments', hi: 'ऐतिहासिक स्मारक' },
      { file: '2-Forts & Palaces.json', en: 'Forts & Palaces', hi: 'किले और महल' },
      { file: '3-Memorials (Samadhis).json', en: 'Memorials (Samadhis)', hi: 'समाधियां' },
      { file: '4-Caves & Rock-Cut.json', en: 'Caves & Rock-Cut', hi: 'गुफाएं और शिलाकृत' },
      { file: '5-Famous Temples.json', en: 'Famous Temples', hi: 'प्रसिद्ध मंदिर' },
      { file: '6-Buddhist Sites.json', en: 'Buddhist Sites', hi: 'बौद्ध स्थल' },
      { file: '7-Mosques & Churches.json', en: 'Mosques & Churches', hi: 'मस्जिदें और चर्च' },
      { file: '8-Research Institutes.json', en: 'Research Institutes', hi: 'अनुसंधान संस्थान' },
      { file: '9-City Nicknames.json', en: 'City Nicknames', hi: 'शहरों के उपनाम' },
      { file: '10-Cities on Rivers.json', en: 'Cities on Rivers', hi: 'नदियों पर शहर' },
      { file: '11-Lakes & Waterfalls.json', en: 'Lakes & Waterfalls', hi: 'झीलें और जलप्रपात' },
      { file: '12-Hill Stations.json', en: 'Hill Stations', hi: 'हिल स्टेशन' },
      { file: '13-Beaches & Islands.json', en: 'Beaches & Islands', hi: 'समुद्र तट और द्वीप' },
      { file: '14-UNESCO Sites.json', en: 'UNESCO Sites', hi: 'UNESCO स्थल' },
      { file: '15-Wonders of India.json', en: 'Wonders of India', hi: 'भारत के अजूबे' },
      { file: '16-Botanic Gardens.json', en: 'Botanic Gardens', hi: 'वनस्पति उद्यान' },
    ],
  },
  {
    key: 'technology', folder: '19-Technology', emoji: '🚀',
    en: { name: 'Technology', desc: 'ISRO, DRDO, AI & Cyber' },
    hi: { name: 'प्रौद्योगिकी', desc: 'इसरो, डीआरडीओ, AI और साइबर' },
    accent: '#5e35b1',
    exams: ['rrb_ntpc', 'ssc_cgl', 'ssc_cpo', 'upsc_cse', 'agniveer_navy_af', 'ugc_net', 'ib_acio'],
    chapters: [
      { file: '1-ISRO Missions.json', en: 'ISRO Missions', hi: 'ISRO मिशन' },
      { file: '2-Satellites.json', en: 'Satellites', hi: 'उपग्रह' },
      { file: '3-Orbits.json', en: 'Orbits', hi: 'कक्षाएं' },
      { file: '4-Missiles of India.json', en: 'Missiles of India', hi: 'भारत की मिसाइलें' },
      { file: '5-Aircrafts.json', en: 'Aircrafts', hi: 'विमान' },
      { file: '6-Submarines.json', en: 'Submarines', hi: 'पनडुब्बियां' },
      { file: '7-Artificial Intelligence.json', en: 'Artificial Intelligence', hi: 'कृत्रिम बुद्धिमत्ता' },
      { file: '8-5G & 6G.json', en: '5G & 6G', hi: '5G और 6G' },
      { file: '9-Cyber Security.json', en: 'Cyber Security', hi: 'साइबर सुरक्षा' },
      { file: '10-Biotechnology.json', en: 'Biotechnology', hi: 'जैव प्रौद्योगिकी' },
      { file: '11-Nanotechnology.json', en: 'Nanotechnology', hi: 'नैनो प्रौद्योगिकी' },
      { file: '12-Nuclear Power.json', en: 'Nuclear Power', hi: 'परमाणु ऊर्जा' },
      { file: '13-India\'s Program.json', en: "India's Programs", hi: 'भारत के कार्यक्रम' },
    ],
  },
  {
    key: 'railways', folder: '20-Railways', emoji: '🚆',
    en: { name: 'Indian Railways', desc: 'Zones, Trains, Budget' },
    hi: { name: 'भारतीय रेल', desc: 'ज़ोन, ट्रेनें, बजट' },
    accent: '#e53935',
    exams: ['rrb_ntpc', 'rrb_group_d', 'rrb_alp', 'rpf_constable'],
    chapters: [
      { file: '1-Railway Zones.json', en: 'Railway Zones', hi: 'रेलवे ज़ोन' },
      { file: '2-Divisions.json', en: 'Divisions', hi: 'मंडल' },
      { file: '3-Station Codes.json', en: 'Station Codes', hi: 'स्टेशन कोड' },
      { file: '4-History & Milestones.json', en: 'History & Milestones', hi: 'इतिहास और मील के पत्थर' },
      { file: '5-Railway Budget.json', en: 'Railway Budget', hi: 'रेल बजट' },
      { file: '6-Mascots & Logos.json', en: 'Mascots & Logos', hi: 'मस्कॉट और लोगो' },
      { file: '7-Famous Trains.json', en: 'Famous Trains', hi: 'प्रसिद्ध ट्रेनें' },
      { file: '8-Luxury Trains.json', en: 'Luxury Trains', hi: 'लक्जरी ट्रेनें' },
      { file: '9-UNESCO Railways.json', en: 'UNESCO Railways', hi: 'UNESCO रेलवे' },
      { file: '10-Production Units.json', en: 'Production Units', hi: 'उत्पादन इकाइयां' },
      { file: '11-Gauges & Tracks.json', en: 'Gauges & Tracks', hi: 'गेज और ट्रैक' },
      { file: '12-Bridges & Tunnels.json', en: 'Bridges & Tunnels', hi: 'पुल और सुरंगें' },
      { file: '13-Green Railways.json', en: 'Green Railways', hi: 'हरित रेलवे' },
      { file: '14-RPF Operations.json', en: 'RPF Operations', hi: 'RPF संचालन' },
      { file: '15-Railway Board.json', en: 'Railway Board', hi: 'रेलवे बोर्ड' },
      { file: '16-PSUs & Subsidiaries.json', en: 'PSUs & Subsidiaries', hi: 'PSU और सहायक कंपनियां' },
    ],
  },
  {
    key: 'environment', folder: '21-Environment', emoji: '🌿',
    en: { name: 'Environment', desc: 'Ecology, Parks, Climate' },
    hi: { name: 'पर्यावरण', desc: 'पारिस्थितिकी, उद्यान, जलवायु' },
    accent: '#388e3c',
    exams: ['ssc_cgl', 'ssc_cpo', 'up_police', 'upsc_cse', 'upsc_cds', 'upsc_capf', 'nda', 'ctet', 'kvs_nvs', 'ugc_net', 'uptet', 'reet', 'uppsc', 'mppsc', 'ukpsc', 'upsssc_pet', 'up_forest_guard', 'raj_forest_guard', 'mp_forest_guard', 'jharkhand_forest_guard', 'bihar_forest_guard', 'haryana_forest_guard', 'agriculture_supervisor', 'epfo_ssa_eo', 'fci_manager'],
    chapters: [
      { file: '1-Ecology & Ecosystems.json', en: 'Ecology & Ecosystems', hi: 'पारिस्थितिकी और पारिस्थितिकी तंत्र' },
      { file: '2-Biodiversity Hotspots.json', en: 'Biodiversity Hotspots', hi: 'जैव विविधता हॉटस्पॉट' },
      { file: '3-Biotic Interaction.json', en: 'Biotic Interaction', hi: 'जैविक अंतःक्रिया' },
      { file: '4-Air & Water Pollution.json', en: 'Air & Water Pollution', hi: 'वायु और जल प्रदूषण' },
      { file: '5-Waste Management.json', en: 'Waste Management', hi: 'अपशिष्ट प्रबंधन' },
      { file: '6-Noise & Radiation.json', en: 'Noise & Radiation', hi: 'ध्वनि और विकिरण' },
      { file: '7-Ramsar Sites.json', en: 'Ramsar Sites', hi: 'रामसर स्थल' },
      { file: '8-Project Tiger & Elephant.json', en: 'Project Tiger & Elephant', hi: 'प्रोजेक्ट टाइगर और हाथी' },
      { file: '9-National Parks.json', en: 'National Parks', hi: 'राष्ट्रीय उद्यान' },
      { file: '10-Ozone & Protocols.json', en: 'Ozone & Protocols', hi: 'ओज़ोन और प्रोटोकॉल' },
      { file: '11-Climate Change.json', en: 'Climate Change', hi: 'जलवायु परिवर्तन' },
      { file: '12-Env Summits (COP).json', en: 'Environment Summits', hi: 'पर्यावरण शिखर सम्मेलन' },
      { file: '13-Environmental Acts.json', en: 'Environmental Acts', hi: 'पर्यावरण अधिनियम' },
      { file: '14-Sustainable Goals.json', en: 'Sustainable Goals', hi: 'सतत विकास लक्ष्य' },
      { file: '15-Renewable Energy.json', en: 'Renewable Energy', hi: 'नवीकरणीय ऊर्जा' },
    ],
  },
  {
    key: 'computer', folder: '22-Computer', emoji: '💻',
    en: { name: 'Computers', desc: 'Hardware, Software, Networking' },
    hi: { name: 'कंप्यूटर', desc: 'हार्डवेयर, सॉफ्टवेयर, नेटवर्किंग' },
    accent: '#1e88e5',
    exams: ['rrb_ntpc', 'ssc_cgl', 'ssc_chsl', 'ssc_cpo', 'rrb_alp', 'ugc_net', 'ssc_mts'],
    chapters: [
      { file: '1-Generations.json', en: 'Generations', hi: 'पीढ़ियां' },
      { file: '2-Memory Units.json', en: 'Memory Units', hi: 'मेमोरी इकाइयां' },
      { file: '3-InputOutput.json', en: 'Input/Output', hi: 'इनपुट/आउटपुट' },
      { file: '4-Shortcut Keys.json', en: 'Shortcut Keys', hi: 'शॉर्टकट कुंजी' },
      { file: '5-MS Excel.json', en: 'MS Excel', hi: 'MS Excel' },
      { file: '6-File Extensions.json', en: 'File Extensions', hi: 'फाइल एक्सटेंशन' },
      { file: '7-DBMS Basics.json', en: 'DBMS Basics', hi: 'DBMS मूल बातें' },
      { file: '8-Data Structures.json', en: 'Data Structures', hi: 'डेटा संरचनाएं' },
      { file: '9-OSI Model.json', en: 'OSI Model', hi: 'OSI मॉडल' },
      { file: '10-Protocols.json', en: 'Protocols', hi: 'प्रोटोकॉल' },
      { file: '11-Languages.json', en: 'Programming Languages', hi: 'प्रोग्रामिंग भाषाएं' },
      { file: '12-Binary System.json', en: 'Binary System', hi: 'बाइनरी सिस्टम' },
    ],
  },
  {
    key: 'bihar_gk', folder: '23-Bihar GK', emoji: '🏛️',
    en: { name: 'Bihar GK', desc: 'Bihar state-specific GK' },
    hi: { name: 'बिहार GK', desc: 'बिहार राज्य विशेष GK' },
    accent: '#880e4f',
    exams: ['bihar_police', 'bpsc', 'stet_bihar', 'bssc', 'bihar_forest_guard', 'bihar_jail_warder'],
    chapters: [
      { file: '1-bihar_basics.json', en: 'Bihar Basics', hi: 'बिहार मूल बातें' },
      { file: '2-bihar_districts_divisions.json', en: 'Districts & Divisions', hi: 'जिले और प्रमंडल' },
      { file: '3-bihar_quick_facts.json', en: 'Quick Facts', hi: 'त्वरित तथ्य' },
      { file: '4-bihar_rivers_bridges.json', en: 'Rivers & Bridges', hi: 'नदियां और पुल' },
      { file: '5-bihar_ancient_history.json', en: 'Ancient History', hi: 'प्राचीन इतिहास' },
      { file: '6-bihar_medieval_history.json', en: 'Medieval History', hi: 'मध्यकालीन इतिहास' },
      { file: '7-bihar_freedom_movement.json', en: 'Freedom Movement', hi: 'स्वतंत्रता आंदोलन' },
      { file: '8-bihar_personalities.json', en: 'Personalities', hi: 'प्रसिद्ध व्यक्तित्व' },
      { file: '9-bihar_rivers.json', en: 'Rivers', hi: 'नदियां' },
      { file: '10-bihar_climate_soils.json', en: 'Climate & Soils', hi: 'जलवायु और मिट्टी' },
      { file: '11-bihar_agriculture.json', en: 'Agriculture', hi: 'कृषि' },
      { file: '12-bihar_wildlife_parks.json', en: 'Wildlife & Parks', hi: 'वन्यजीव और उद्यान' },
      { file: '13-bihar_minerals_industry.json', en: 'Minerals & Industry', hi: 'खनिज और उद्योग' },
      { file: '14-bihar_state_government.json', en: 'State Government', hi: 'राज्य सरकार' },
      { file: '15-bihar_administration.json', en: 'Administration', hi: 'प्रशासन' },
      { file: '16-bihar_panchayati_raj.json', en: 'Panchayati Raj', hi: 'पंचायती राज' },
      { file: '17-bihar_economy.json', en: 'Economy', hi: 'अर्थव्यवस्था' },
      { file: '18-bihar_schemes_projects.json', en: 'Schemes & Projects', hi: 'योजनाएं और परियोजनाएं' },
      { file: '19-bihar_festivals_fairs.json', en: 'Festivals & Fairs', hi: 'त्यौहार और मेले' },
      { file: '20-bihar_art_culture.json', en: 'Art & Culture', hi: 'कला और संस्कृति' },
      { file: '21-bihar_tourism_heritage.json', en: 'Tourism & Heritage', hi: 'पर्यटन और विरासत' },
      { file: '22-bihar_sports_awards.json', en: 'Sports & Awards', hi: 'खेल और पुरस्कार' },
    ],
  },
  {
    key: 'police_gk', folder: '26-Police GK', emoji: '👮',
    en: { name: 'Police GK', desc: 'Ranks, Laws, FIR & more' },
    hi: { name: 'पुलिस GK', desc: 'रैंक, कानून, FIR और अधिक' },
    accent: '#1a237e',
    exams: ['up_police', 'delhi_police', 'bihar_police', 'rpf_constable', 'ssc_gd', 'ssc_cpo', 'upsc_capf', 'haryana_police', 'rajasthan_police', 'mp_police', 'raj_jail_prahari', 'bihar_jail_warder', 'up_jail_prahari', 'mp_jail_prahari'],
    chapters: [
      { file: '1-Police Ranks.json', en: 'Police Ranks', hi: 'पुलिस रैंक' },
      { file: '2-Insignia Guide.json', en: 'Insignia Guide', hi: 'बैज गाइड' },
      { file: '3-Promotion Flow.json', en: 'Promotion Flow', hi: 'पदोन्नति क्रम' },
      { file: '4-FIR.json', en: 'FIR', hi: 'FIR' },
      { file: '5-Arrest Rights.json', en: 'Arrest Rights', hi: 'गिरफ्तारी अधिकार' },
      { file: '6-Important IPC.json', en: 'Important IPC', hi: 'महत्वपूर्ण IPC' },
      { file: '7-Zones & Ranges.json', en: 'Zones & Ranges', hi: 'ज़ोन और रेंज' },
      { file: '8-Police Districts.json', en: 'Police Districts', hi: 'पुलिस जिले' },
      { file: '9-Headquarters.json', en: 'Headquarters', hi: 'मुख्यालय' },
      { file: '10-BMP.json', en: 'BMP', hi: 'BMP' },
      { file: '11-DIAL 112.json', en: 'DIAL 112', hi: 'डायल 112' },
      { file: '12-Traffic.json', en: 'Traffic', hi: 'ट्रैफिक' },
      { file: '13-Motto.json', en: 'Motto', hi: 'आदर्श वाक्य' },
      { file: '14-Police Act 2007.json', en: 'Police Act 2007', hi: 'पुलिस अधिनियम 2007' },
    ],
  },
  {
    key: 'up_gk', folder: '27-UP GK', emoji: '🏛️',
    en: { name: 'UP GK', desc: 'Uttar Pradesh state GK' },
    hi: { name: 'उत्तर प्रदेश GK', desc: 'उत्तर प्रदेश राज्य GK' },
    accent: '#bf360c',
    exams: ['up_police', 'uppsc', 'uptet', 'super_tet', 'upsssc_pet', 'up_forest_guard', 'up_jail_prahari', 'up_lekhpal', 'gram_panchayat_vdo'],
    chapters: [
      { file: '1-UP History.json', en: 'UP History', hi: 'UP इतिहास' },
      { file: '2-UP Geography Rivers Districts.json', en: 'Geography, Rivers & Districts', hi: 'भूगोल, नदियां और जिले' },
      { file: '3-UP Government Schemes.json', en: 'Government Schemes', hi: 'सरकारी योजनाएं' },
      { file: '4-UP Administration CM Governors.json', en: 'Administration & CM/Governors', hi: 'प्रशासन और CM/राज्यपाल' },
      { file: '5-UP Economy Industries.json', en: 'Economy & Industries', hi: 'अर्थव्यवस्था और उद्योग' },
      { file: '6-UP Art Culture Festivals.json', en: 'Art, Culture & Festivals', hi: 'कला, संस्कृति और त्यौहार' },
      { file: '7-UP Famous Personalities.json', en: 'Famous Personalities', hi: 'प्रसिद्ध व्यक्तित्व' },
    ],
  },
  {
    key: 'rajasthan_gk', folder: '28-Rajasthan GK', emoji: '🏜️',
    en: { name: 'Rajasthan GK', desc: 'Rajasthan state GK' },
    hi: { name: 'राजस्थान GK', desc: 'राजस्थान राज्य GK' },
    accent: '#e65100',
    exams: ['rpsc_ras', 'rajasthan_police', 'rsmssb', 'reet', 'raj_forest_guard', 'raj_jail_prahari', 'raj_patwari'],
    chapters: [
      { file: '1-Rajasthan History Kingdoms.json', en: 'History & Kingdoms', hi: 'इतिहास और राज्य' },
      { file: '2-Rajasthan Forts Palaces.json', en: 'Forts & Palaces', hi: 'किले और महल' },
      { file: '3-Rajasthan Geography.json', en: 'Geography', hi: 'भूगोल' },
      { file: '4-Rajasthan Art Culture Festivals.json', en: 'Art, Culture & Festivals', hi: 'कला, संस्कृति और त्यौहार' },
      { file: '5-Rajasthan Tribes Communities.json', en: 'Tribes & Communities', hi: 'जनजातियां और समुदाय' },
      { file: '6-Rajasthan Economy Agriculture.json', en: 'Economy & Agriculture', hi: 'अर्थव्यवस्था और कृषि' },
      { file: '7-Rajasthan Wildlife National Parks.json', en: 'Wildlife & National Parks', hi: 'वन्यजीव और राष्ट्रीय उद्यान' },
      { file: '8-Rajasthan CM Governors Schemes.json', en: 'CM, Governors & Schemes', hi: 'CM, राज्यपाल और योजनाएं' },
      { file: '9-Rajasthan Famous Personalities.json', en: 'Famous Personalities', hi: 'प्रसिद्ध व्यक्तित्व' },
    ],
  },
  {
    key: 'mp_gk', folder: '29-MP GK', emoji: '🏛️',
    en: { name: 'MP GK', desc: 'Madhya Pradesh state GK' },
    hi: { name: 'मध्य प्रदेश GK', desc: 'मध्य प्रदेश राज्य GK' },
    accent: '#4e342e',
    exams: ['mppsc', 'mp_police', 'mpesb_vyapam', 'mp_forest_guard', 'mp_jail_prahari', 'mp_patwari'],
    chapters: [
      { file: '1-MP History Heritage Sites.json', en: 'History & Heritage', hi: 'इतिहास और विरासत' },
      { file: '2-MP Geography Rivers Mountains.json', en: 'Geography, Rivers & Mountains', hi: 'भूगोल, नदियां और पर्वत' },
      { file: '3-MP National Parks Wildlife.json', en: 'National Parks & Wildlife', hi: 'राष्ट्रीय उद्यान और वन्यजीव' },
      { file: '4-MP Tribes Culture.json', en: 'Tribes & Culture', hi: 'जनजातियां और संस्कृति' },
      { file: '5-MP Art Crafts Dance.json', en: 'Art, Crafts & Dance', hi: 'कला, शिल्प और नृत्य' },
      { file: '6-MP Economy Agriculture.json', en: 'Economy & Agriculture', hi: 'अर्थव्यवस्था और कृषि' },
      { file: '7-MP CM Governors Schemes.json', en: 'CM, Governors & Schemes', hi: 'CM, राज्यपाल और योजनाएं' },
      { file: '8-MP Famous Personalities.json', en: 'Famous Personalities', hi: 'प्रसिद्ध व्यक्तित्व' },
    ],
  },
  {
    key: 'maharashtra_gk', folder: '30-Maharashtra GK', emoji: '🏛️',
    en: { name: 'Maharashtra GK', desc: 'Maharashtra state GK' },
    hi: { name: 'महाराष्ट्र GK', desc: 'महाराष्ट्र राज्य GK' },
    accent: '#ff6f00',
    exams: [],
    chapters: [
      { file: '1-Maratha Empire Shivaji.json', en: 'Maratha Empire & Shivaji', hi: 'मराठा साम्राज्य और शिवाजी' },
      { file: '2-Peshwa Period Maratha Wars.json', en: 'Peshwa Period & Maratha Wars', hi: 'पेशवा काल और मराठा युद्ध' },
      { file: '3-Maharashtra Forts Heritage.json', en: 'Forts & Heritage', hi: 'किले और विरासत' },
      { file: '4-Maharashtra Freedom Struggle.json', en: 'Freedom Struggle', hi: 'स्वतंत्रता संग्राम' },
      { file: '5-Maharashtra Geography Rivers.json', en: 'Geography & Rivers', hi: 'भूगोल और नदियां' },
      { file: '6-Maharashtra Art Culture.json', en: 'Art & Culture', hi: 'कला और संस्कृति' },
      { file: '7-Maharashtra Economy Industries.json', en: 'Economy & Industries', hi: 'अर्थव्यवस्था और उद्योग' },
      { file: '8-Maharashtra CM Governors Schemes.json', en: 'CM, Governors & Schemes', hi: 'CM, राज्यपाल और योजनाएं' },
      { file: '9-Maharashtra Famous Personalities.json', en: 'Famous Personalities', hi: 'प्रसिद्ध व्यक्तित्व' },
    ],
  },
  {
    key: 'gujarat_gk', folder: '31-Gujarat GK', emoji: '🏛️',
    en: { name: 'Gujarat GK', desc: 'Gujarat state GK' },
    hi: { name: 'गुजरात GK', desc: 'गुजरात राज्य GK' },
    accent: '#00695c',
    exams: [],
    chapters: [
      { file: '1-Gujarat Harappan Ancient History.json', en: 'Ancient History & Harappan', hi: 'प्राचीन इतिहास और हड़प्पा' },
      { file: '2-Gujarat Freedom Struggle Gandhi.json', en: 'Freedom Struggle & Gandhi', hi: 'स्वतंत्रता संग्राम और गांधी' },
      { file: '3-Gujarat Economy Industries.json', en: 'Economy & Industries', hi: 'अर्थव्यवस्था और उद्योग' },
      { file: '4-Gujarat Geography Coastline Rann.json', en: 'Geography, Coastline & Rann', hi: 'भूगोल, तटरेखा और रण' },
      { file: '5-Gujarat Art Culture Festivals.json', en: 'Art, Culture & Festivals', hi: 'कला, संस्कृति और त्यौहार' },
      { file: '6-Gujarat Heritage Sites Temples.json', en: 'Heritage Sites & Temples', hi: 'विरासत स्थल और मंदिर' },
      { file: '7-Gujarat Wildlife Gir Forest.json', en: 'Wildlife & Gir Forest', hi: 'वन्यजीव और गिर वन' },
      { file: '8-Gujarat CM Governors Schemes.json', en: 'CM, Governors & Schemes', hi: 'CM, राज्यपाल और योजनाएं' },
      { file: '9-Gujarat Famous Personalities.json', en: 'Famous Personalities', hi: 'प्रसिद्ध व्यक्तित्व' },
    ],
  },
  {
    key: 'haryana_gk', folder: '32-Haryana GK', emoji: '🏛️',
    en: { name: 'Haryana GK', desc: 'Haryana state GK' },
    hi: { name: 'हरियाणा GK', desc: 'हरियाणा राज्य GK' },
    accent: '#33691e',
    exams: ['hpsc_hcs', 'haryana_police', 'haryana_forest_guard', 'haryana_patwari'],
    chapters: [
      { file: '1-Haryana History Panipat Battles.json', en: 'History & Panipat Battles', hi: 'इतिहास और पानीपत युद्ध' },
      { file: '2-Haryana Sports Olympic Medals.json', en: 'Sports & Olympic Medals', hi: 'खेल और ओलंपिक पदक' },
      { file: '3-Haryana Geography Rivers.json', en: 'Geography & Rivers', hi: 'भूगोल और नदियां' },
      { file: '4-Haryana Economy Agriculture.json', en: 'Economy & Agriculture', hi: 'अर्थव्यवस्था और कृषि' },
      { file: '5-Haryana Art Culture Festivals.json', en: 'Art, Culture & Festivals', hi: 'कला, संस्कृति और त्यौहार' },
      { file: '6-Haryana CM Governors Schemes.json', en: 'CM, Governors & Schemes', hi: 'CM, राज्यपाल और योजनाएं' },
      { file: '7-Haryana Famous Personalities.json', en: 'Famous Personalities', hi: 'प्रसिद्ध व्यक्तित्व' },
    ],
  },
  {
    key: 'jharkhand_gk', folder: '33-Jharkhand GK', emoji: '🏛️',
    en: { name: 'Jharkhand GK', desc: 'Jharkhand state GK' },
    hi: { name: 'झारखंड GK', desc: 'झारखंड राज्य GK' },
    accent: '#827717',
    exams: ['jharkhand_forest_guard'],
    chapters: [
      { file: '1-Jharkhand Formation History.json', en: 'Formation & History', hi: 'गठन और इतिहास' },
      { file: '2-Jharkhand Tribes Culture.json', en: 'Tribes & Culture', hi: 'जनजातियां और संस्कृति' },
      { file: '3-Jharkhand Minerals Industries.json', en: 'Minerals & Industries', hi: 'खनिज और उद्योग' },
      { file: '4-Jharkhand Geography Plateau.json', en: 'Geography & Plateau', hi: 'भूगोल और पठार' },
      { file: '5-Jharkhand Art Festivals Dance.json', en: 'Art, Festivals & Dance', hi: 'कला, त्यौहार और नृत्य' },
      { file: '6-Jharkhand CM Governors Schemes.json', en: 'CM, Governors & Schemes', hi: 'CM, राज्यपाल और योजनाएं' },
      { file: '7-Jharkhand Famous Personalities.json', en: 'Famous Personalities', hi: 'प्रसिद्ध व्यक्तित्व' },
    ],
  },
  {
    key: 'defence_gk', folder: '34-Defence GK', emoji: '🎖️',
    en: { name: 'Defence GK', desc: 'Army, Navy, Air Force & more' },
    hi: { name: 'रक्षा GK', desc: 'सेना, नौसेना, वायु सेना और अधिक' },
    accent: '#263238',
    exams: ['nda', 'agniveer_army', 'agniveer_navy_af', 'upsc_cds', 'upsc_capf', 'rpf_constable', 'ssc_gd', 'aissee_sainik'],
    chapters: [
      { file: '1-India Wars 1947 1962 1965.json', en: 'Wars: 1947, 1962, 1965', hi: 'युद्ध: 1947, 1962, 1965' },
      { file: '2-India Wars 1971 Kargil Ops.json', en: 'Wars: 1971 & Kargil', hi: 'युद्ध: 1971 और कारगिल' },
      { file: '3-Military Awards PVC Recipients.json', en: 'Military Awards & PVC', hi: 'सैन्य पुरस्कार और PVC' },
      { file: '4-India Missile Programme.json', en: 'Missile Programme', hi: 'मिसाइल कार्यक्रम' },
      { file: '5-Indian Army Structure Ranks.json', en: 'Army Structure & Ranks', hi: 'सेना संरचना और रैंक' },
      { file: '6-Indian Navy Ships Submarines.json', en: 'Navy Ships & Submarines', hi: 'नौसेना जहाज और पनडुब्बी' },
      { file: '7-Indian Air Force Aircraft.json', en: 'Air Force & Aircraft', hi: 'वायु सेना और विमान' },
      { file: '8-Nuclear Programme Policy.json', en: 'Nuclear Programme & Policy', hi: 'परमाणु कार्यक्रम और नीति' },
      { file: '9-Paramilitary BSF CRPF CISF.json', en: 'Paramilitary Forces', hi: 'अर्धसैनिक बल' },
      { file: '10-DRDO HAL Defence Organisations.json', en: 'DRDO, HAL & Defence Orgs', hi: 'DRDO, HAL और रक्षा संगठन' },
      { file: '11-Military Exercises Bilateral.json', en: 'Military Exercises', hi: 'सैन्य अभ्यास' },
      { file: '12-Coast Guard NSG Special Forces.json', en: 'Coast Guard & Special Forces', hi: 'तटरक्षक और विशेष बल' },
    ],
  },
  {
    key: 'govt_schemes', folder: '35-Government Schemes GK', emoji: '📋',
    en: { name: 'Government Schemes', desc: 'Welfare, health & development' },
    hi: { name: 'सरकारी योजनाएं', desc: 'कल्याण, स्वास्थ्य और विकास' },
    accent: '#0d47a1',
    exams: ['upsc_cse', 'uppsc', 'upsssc_pet', 'mpesb_vyapam', 'up_lekhpal', 'raj_patwari', 'mp_patwari', 'haryana_patwari', 'gram_panchayat_vdo', 'agriculture_supervisor', 'fci_manager', 'ibps_afo', 'epfo_ssa_eo'],
    chapters: [
      { file: '1-Agriculture Farmer Schemes.json', en: 'Agriculture & Farmer Schemes', hi: 'कृषि और किसान योजनाएं' },
      { file: '2-Health Nutrition Schemes.json', en: 'Health & Nutrition Schemes', hi: 'स्वास्थ्य और पोषण योजनाएं' },
      { file: '3-Government Schemes Housing Urban.json', en: 'Housing & Urban Schemes', hi: 'आवास और शहरी योजनाएं' },
      { file: '4-Financial Inclusion Schemes.json', en: 'Financial Inclusion', hi: 'वित्तीय समावेशन' },
      { file: '5-Government Schemes Women Child.json', en: 'Women & Child Schemes', hi: 'महिला और बाल योजनाएं' },
      { file: '6-Livelihood Employment Schemes.json', en: 'Livelihood & Employment', hi: 'आजीविका और रोजगार' },
      { file: '7-Government Schemes Infrastructure Digital.json', en: 'Infrastructure & Digital', hi: 'बुनियादी ढांचा और डिजिटल' },
      { file: '8-Education Skill Schemes.json', en: 'Education & Skill Schemes', hi: 'शिक्षा और कौशल योजनाएं' },
      { file: '9-Government Schemes Social Welfare.json', en: 'Social Welfare', hi: 'सामाजिक कल्याण' },
      { file: '10-Government Schemes Environment Energy.json', en: 'Environment & Energy', hi: 'पर्यावरण और ऊर्जा' },
    ],
  },
  {
    key: 'constitution_special', folder: '36-Indian Constitution Special', emoji: '📜',
    en: { name: 'Constitution Special', desc: 'In-depth constitutional study' },
    hi: { name: 'संविधान विशेष', desc: 'गहन संवैधानिक अध्ययन' },
    accent: '#4a148c',
    exams: ['upsc_cse', 'uppsc'],
    chapters: [
      { file: '1-Fundamental Rights Art 12 35.json', en: 'Fundamental Rights (Art 12-35)', hi: 'मूल अधिकार (अनु. 12-35)' },
      { file: '2-Constitutional Amendments Major.json', en: 'Major Amendments', hi: 'प्रमुख संशोधन' },
      { file: '3-Landmark Supreme Court Cases.json', en: 'Landmark Supreme Court Cases', hi: 'सुप्रीम कोर्ट के ऐतिहासिक फैसले' },
      { file: '4-President PM Parliament.json', en: 'President, PM & Parliament', hi: 'राष्ट्रपति, PM और संसद' },
      { file: '5-DPSP Fundamental Duties.json', en: 'DPSP & Fundamental Duties', hi: 'DPSP और मूल कर्तव्य' },
      { file: '6-Supreme Court High Courts.json', en: 'Supreme Court & High Courts', hi: 'सुप्रीम कोर्ट और हाई कोर्ट' },
      { file: '7-All 12 Schedules.json', en: 'All 12 Schedules', hi: 'सभी 12 अनुसूचियां' },
      { file: '8-Governor State Legislature.json', en: 'Governor & State Legislature', hi: 'राज्यपाल और राज्य विधानमंडल' },
      { file: '9-Preamble Historical Background.json', en: 'Preamble & History', hi: 'प्रस्तावना और इतिहास' },
      { file: '10-Constitutional Bodies EC CAG.json', en: 'Constitutional Bodies', hi: 'संवैधानिक निकाय' },
      { file: '11-Emergency Provisions 352 356.json', en: 'Emergency Provisions', hi: 'आपातकाल प्रावधान' },
      { file: '12-Panchayati Raj Art 243.json', en: 'Panchayati Raj (Art 243)', hi: 'पंचायती राज (अनु. 243)' },
      { file: '13-Union State Relations.json', en: 'Union-State Relations', hi: 'केंद्र-राज्य संबंध' },
    ],
  },
  {
    key: 'agriculture', folder: '37-Indian Agriculture', emoji: '🌾',
    en: { name: 'Indian Agriculture', desc: 'Crops, irrigation & farming' },
    hi: { name: 'भारतीय कृषि', desc: 'फसलें, सिंचाई और खेती' },
    accent: '#33691e',
    exams: ['agriculture_supervisor', 'fci_manager', 'ibps_afo'],
    chapters: [
      { file: '1-Crops Top Producing States.json', en: 'Crops & Top Producing States', hi: 'फसलें और शीर्ष उत्पादक राज्य' },
      { file: '2-Agricultural Revolutions.json', en: 'Agricultural Revolutions', hi: 'कृषि क्रांतियां' },
      { file: '3-MSP APMC Procurement.json', en: 'MSP, APMC & Procurement', hi: 'MSP, APMC और खरीद' },
      { file: '4-Soil Types India.json', en: 'Soil Types of India', hi: 'भारत की मृदा प्रकार' },
      { file: '5-Irrigation Systems.json', en: 'Irrigation Systems', hi: 'सिंचाई प्रणाली' },
      { file: '6-Agricultural Institutions.json', en: 'Agricultural Institutions', hi: 'कृषि संस्थान' },
      { file: '7-Land Reforms History.json', en: 'Land Reforms History', hi: 'भूमि सुधार इतिहास' },
      { file: '8-Agricultural Schemes PM Kisan.json', en: 'Agricultural Schemes & PM Kisan', hi: 'कृषि योजनाएं और PM किसान' },
    ],
  },
  {
    key: 'national_movement', folder: '38-Indian National Movement', emoji: '🇮🇳',
    en: { name: 'National Movement', desc: 'Freedom struggle & leaders' },
    hi: { name: 'राष्ट्रीय आंदोलन', desc: 'स्वतंत्रता संग्राम और नेता' },
    accent: '#e65100',
    exams: ['upsc_cse', 'upsc_cds', 'upsc_capf', 'uppsc', 'bpsc', 'rpsc_ras', 'mppsc', 'hpsc_hcs', 'ukpsc', 'upsssc_pet'],
    chapters: [
      { file: '1-Non Cooperation Civil Disobedience.json', en: 'Non-Cooperation & Civil Disobedience', hi: 'असहयोग और सविनय अवज्ञा' },
      { file: '2-Quit India 1942 INA Bose.json', en: 'Quit India 1942 & INA-Bose', hi: 'भारत छोड़ो 1942 और INA-बोस' },
      { file: '3-Revolt 1857 Causes Leaders.json', en: 'Revolt of 1857', hi: '1857 का विद्रोह' },
      { file: '4-Revolutionary Movement Bhagat Singh.json', en: 'Revolutionary Movement & Bhagat Singh', hi: 'क्रांतिकारी आंदोलन और भगत सिंह' },
      { file: '5-Gandhian Era Satyagrahas.json', en: 'Gandhian Era & Satyagrahas', hi: 'गांधीवादी युग और सत्याग्रह' },
      { file: '6-Transfer Power Partition 1947.json', en: 'Transfer of Power & Partition', hi: 'सत्ता हस्तांतरण और विभाजन' },
      { file: '7-Early Nationalism INC Formation.json', en: 'Early Nationalism & INC Formation', hi: 'प्रारंभिक राष्ट्रवाद और INC' },
      { file: '8-Moderates Extremists Lal Bal Pal.json', en: 'Moderates, Extremists & Lal-Bal-Pal', hi: 'उदारवादी, उग्रवादी और लाल-बाल-पाल' },
      { file: '9-Partition Bengal Swadeshi.json', en: 'Partition of Bengal & Swadeshi', hi: 'बंगाल विभाजन और स्वदेशी' },
      { file: '10-INC Sessions Presidents.json', en: 'INC Sessions & Presidents', hi: 'INC अधिवेशन और अध्यक्ष' },
      { file: '11-Important Acts Rowlatt Montagu.json', en: 'Important Acts (Rowlatt, Montagu)', hi: 'महत्वपूर्ण अधिनियम' },
      { file: '12-Women Freedom Fighters.json', en: 'Women Freedom Fighters', hi: 'महिला स्वतंत्रता सेनानी' },
    ],
  },
  {
    key: 'international_relations', folder: '39-International Relations', emoji: '🌐',
    en: { name: 'International Relations', desc: 'Diplomacy, alliances & law' },
    hi: { name: 'अंतर्राष्ट्रीय संबंध', desc: 'कूटनीति, गठबंधन और कानून' },
    accent: '#01579b',
    exams: ['upsc_cse', 'ib_acio'],
    chapters: [
      { file: '1-India China Relations LAC.json', en: 'India-China Relations & LAC', hi: 'भारत-चीन संबंध और LAC' },
      { file: '2-India Pakistan Relations.json', en: 'India-Pakistan Relations', hi: 'भारत-पाकिस्तान संबंध' },
      { file: '3-G20 BRICS SCO QUAD.json', en: 'G20, BRICS, SCO & QUAD', hi: 'G20, BRICS, SCO और QUAD' },
      { file: '4-UN WHO IMF World Bank.json', en: 'UN, WHO, IMF & World Bank', hi: 'UN, WHO, IMF और विश्व बैंक' },
      { file: '5-Nuclear Policy NPT CTBT NSG.json', en: 'Nuclear Policy: NPT, CTBT, NSG', hi: 'परमाणु नीति: NPT, CTBT, NSG' },
      { file: '6-India USA Relations Agreements.json', en: 'India-USA Relations', hi: 'भारत-USA संबंध' },
      { file: '7-India Foreign Policy NAM.json', en: 'India Foreign Policy & NAM', hi: 'भारत की विदेश नीति और NAM' },
      { file: '8-India Neighbours Nepal BD SL.json', en: 'India & Neighbours (Nepal, BD, SL)', hi: 'भारत और पड़ोसी देश' },
      { file: '9-India Russia Israel Relations.json', en: 'India-Russia & Israel Relations', hi: 'भारत-रूस और इजरायल संबंध' },
      { file: '10-Major Treaties Agreements.json', en: 'Major Treaties & Agreements', hi: 'प्रमुख संधियां और समझौते' },
    ],
  },
  {
    key: 'disaster_mgmt', folder: '40-Disaster Management', emoji: '🚨',
    en: { name: 'Disaster Management', desc: 'Emergency response & preparedness' },
    hi: { name: 'आपदा प्रबंधन', desc: 'आपातकालीन प्रतिक्रिया और तैयारी' },
    accent: '#b71c1c',
    exams: ['ukpsc', 'raj_jail_prahari'],
    chapters: [
      { file: '1-India Major Disasters History.json', en: 'Major Disasters in India', hi: 'भारत में प्रमुख आपदाएं' },
      { file: '2-NDMA NDRF Framework.json', en: 'NDMA & NDRF Framework', hi: 'NDMA और NDRF ढांचा' },
      { file: '3-Earthquake Seismic Zones.json', en: 'Earthquake & Seismic Zones', hi: 'भूकंप और भूकंपीय क्षेत्र' },
      { file: '4-Cyclone Flood Management.json', en: 'Cyclone & Flood Management', hi: 'चक्रवात और बाढ़ प्रबंधन' },
      { file: '5-Sendai Hyogo Framework.json', en: 'Sendai & Hyogo Framework', hi: 'सेंडाई और हयोगो ढांचा' },
      { file: '6-Types Disasters Natural Manmade.json', en: 'Types of Disasters', hi: 'आपदाओं के प्रकार' },
      { file: '7-Disaster Preparedness Response.json', en: 'Preparedness & Response', hi: 'तैयारी और प्रतिक्रिया' },
    ],
  },
  {
    key: 'economy_advanced', folder: '41-Indian Economy Advanced', emoji: '📊',
    en: { name: 'Economy Advanced', desc: 'Banking, FDI, stock market' },
    hi: { name: 'अर्थव्यवस्था उन्नत', desc: 'बैंकिंग, FDI, शेयर बाजार' },
    accent: '#880e4f',
    exams: ['upsc_cse', 'epfo_ssa_eo', 'fci_manager', 'ibps_afo', 'labour_inspector'],
    chapters: [
      { file: '1-Union Budget Fiscal Deficit.json', en: 'Union Budget & Fiscal Deficit', hi: 'केंद्रीय बजट और राजकोषीय घाटा' },
      { file: '2-Monetary Policy RBI Tools.json', en: 'Monetary Policy & RBI Tools', hi: 'मौद्रिक नीति और RBI साधन' },
      { file: '3-Banking System NPA IBC.json', en: 'Banking System, NPA & IBC', hi: 'बैंकिंग प्रणाली, NPA और IBC' },
      { file: '4-GST Tax Structure.json', en: 'GST & Tax Structure', hi: 'GST और कर संरचना' },
      { file: '5-GDP National Income.json', en: 'GDP & National Income', hi: 'GDP और राष्ट्रीय आय' },
      { file: '6-Inflation WPI CPI.json', en: 'Inflation: WPI & CPI', hi: 'मुद्रास्फीति: WPI और CPI' },
      { file: '7-External Sector FDI FPI BoP.json', en: 'External Sector: FDI, FPI & BoP', hi: 'बाह्य क्षेत्र: FDI, FPI और BoP' },
      { file: '8-NITI Aayog Planning.json', en: 'NITI Aayog & Planning', hi: 'नीति आयोग और नियोजन' },
      { file: '9-Economic Reforms 1991.json', en: 'Economic Reforms 1991', hi: '1991 के आर्थिक सुधार' },
      { file: '10-India Growth Key Indicators.json', en: 'India Growth & Key Indicators', hi: 'भारत की वृद्धि और मुख्य संकेतक' },
    ],
  },
  {
    key: 'forest_wildlife', folder: '42-Forest and Wildlife GK', emoji: '🌲',
    en: { name: 'Forest & Wildlife', desc: 'Conservation, parks & ecology' },
    hi: { name: 'वन और वन्यजीव', desc: 'संरक्षण, उद्यान और पारिस्थितिकी' },
    accent: '#1b5e20',
    exams: ['up_forest_guard', 'raj_forest_guard', 'mp_forest_guard', 'jharkhand_forest_guard', 'bihar_forest_guard', 'haryana_forest_guard'],
    chapters: [
      { file: '1-Tiger Reserves Project Tiger.json', en: 'Tiger Reserves & Project Tiger', hi: 'टाइगर रिजर्व और प्रोजेक्ट टाइगर' },
      { file: '2-Endangered Species India.json', en: 'Endangered Species of India', hi: 'भारत की संकटग्रस्त प्रजातियां' },
      { file: '3-National Parks Complete List.json', en: 'National Parks (Complete List)', hi: 'राष्ट्रीय उद्यान (पूरी सूची)' },
      { file: '4-Ramsar Wetland Sites.json', en: 'Ramsar Wetland Sites', hi: 'रामसर आर्द्रभूमि स्थल' },
      { file: '5-Wildlife Protection Act 1972.json', en: 'Wildlife Protection Act 1972', hi: 'वन्यजीव संरक्षण अधिनियम 1972' },
      { file: '6-Biosphere Reserves India.json', en: 'Biosphere Reserves of India', hi: 'भारत के जैव मंडल आरक्षित क्षेत्र' },
      { file: '7-Forest Conservation Laws.json', en: 'Forest Conservation Laws', hi: 'वन संरक्षण कानून' },
      { file: '8-IUCN Categories Biodiversity.json', en: 'IUCN Categories & Biodiversity', hi: 'IUCN श्रेणियां और जैव विविधता' },
      { file: '9-Forest Types India.json', en: 'Forest Types of India', hi: 'भारत के वन प्रकार' },
      { file: '10-Migratory Birds Wildlife.json', en: 'Migratory Birds & Wildlife', hi: 'प्रवासी पक्षी और वन्यजीव' },
      { file: '11-NGT CPCB Environment Bodies.json', en: 'NGT, CPCB & Environment Bodies', hi: 'NGT, CPCB और पर्यावरण निकाय' },
    ],
  },
  {
    key: 'labour_laws', folder: '43-Labour Laws', emoji: '⚖️',
    en: { name: 'Labour Laws', desc: 'Employment, wages & safety' },
    hi: { name: 'श्रम कानून', desc: 'रोजगार, मजदूरी और सुरक्षा' },
    accent: '#4527a0',
    exams: ['epfo_ssa_eo', 'labour_inspector'],
    chapters: [
      { file: '1-EPF EPS EDLI EPFO.json', en: 'EPF, EPS, EDLI & EPFO', hi: 'EPF, EPS, EDLI और EPFO' },
      { file: '2-Four Labour Codes 2020.json', en: 'Four Labour Codes 2020', hi: 'चार श्रम संहिताएं 2020' },
      { file: '3-Industrial Disputes Act 1947.json', en: 'Industrial Disputes Act 1947', hi: 'औद्योगिक विवाद अधिनियम 1947' },
      { file: '4-ESI Act ESIC.json', en: 'ESI Act & ESIC', hi: 'ESI अधिनियम और ESIC' },
      { file: '5-Factories Act 1948.json', en: 'Factories Act 1948', hi: 'कारखाना अधिनियम 1948' },
      { file: '6-Maternity Gratuity Wages Acts.json', en: 'Maternity, Gratuity & Wages Acts', hi: 'प्रसूति, ग्रेच्युटी और मजदूरी अधिनियम' },
      { file: '7-Social Security Unorganised.json', en: 'Social Security (Unorganised)', hi: 'असंगठित क्षेत्र सामाजिक सुरक्षा' },
      { file: '8-ILO International Labour.json', en: 'ILO & International Labour', hi: 'ILO और अंतर्राष्ट्रीय श्रम' },
    ],
  },
  {
    key: 'revenue_panchayat', folder: '44-Revenue and Panchayati Raj', emoji: '🏘️',
    en: { name: 'Revenue & Panchayati Raj', desc: 'Land records, revenue & local govt' },
    hi: { name: 'राजस्व और पंचायती राज', desc: 'भूमि अभिलेख, राजस्व और स्थानीय शासन' },
    accent: '#795548',
    exams: ['up_lekhpal', 'raj_patwari', 'mp_patwari', 'haryana_patwari', 'gram_panchayat_vdo'],
    chapters: [
      { file: '1-Panchayati Raj 73rd Amendment.json', en: 'Panchayati Raj & 73rd Amendment', hi: 'पंचायती राज और 73वां संशोधन' },
      { file: '2-Land Records Khasra Khatauni.json', en: 'Land Records: Khasra & Khatauni', hi: 'भूमि अभिलेख: खसरा और खतौनी' },
      { file: '3-Three Tier PR Structure.json', en: 'Three Tier PR Structure', hi: 'तीन स्तरीय पंचायती राज' },
      { file: '4-Land Measurement Bigha Acre.json', en: 'Land Measurement (Bigha, Acre)', hi: 'भूमि माप (बीघा, एकड़)' },
      { file: '5-Revenue System Tehsildar.json', en: 'Revenue System & Tehsildar', hi: 'राजस्व व्यवस्था और तहसीलदार' },
      { file: '6-Municipalities 74th Amendment.json', en: 'Municipalities & 74th Amendment', hi: 'नगरपालिका और 74वां संशोधन' },
      { file: '7-PR Committees Balwantrai.json', en: 'PR Committees & Balwantrai', hi: 'PR समितियां और बलवंतराय' },
      { file: '8-MGNREGA Village Level.json', en: 'MGNREGA at Village Level', hi: 'ग्राम स्तर पर MGNREGA' },
      { file: '9-Land Acquisition Act 2013.json', en: 'Land Acquisition Act 2013', hi: 'भूमि अधिग्रहण अधिनियम 2013' },
    ],
  },
];

// Utility: generate URL slug from topic key
export function topicSlug(key: string): string {
  return key.replace(/_/g, '-');
}

// Utility: generate URL slug from chapter name
export function chapterSlug(chapterEn: string): string {
  return chapterEn
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .trim();
}

// Find topic by URL slug
export function getTopicBySlug(slug: string): Topic | undefined {
  return TOPICS.find(t => topicSlug(t.key) === slug);
}

// Find chapter by topic and chapter slug
export function getChapterBySlug(topic: Topic, slug: string) {
  return topic.chapters.find(c => chapterSlug(c.en) === slug);
}

// Get visible topics (not hidden from list)
export function getVisibleTopics(): Topic[] {
  return TOPICS.filter(t => !t.hiddenFromList);
}

// Count total chapters
export function getTotalChapters(): number {
  return TOPICS.reduce((sum, t) => sum + t.chapters.length, 0);
}

// Count total topics
export function getTotalTopics(): number {
  return getVisibleTopics().length;
}

// Set size config
export const SET_SIZE = 10;

// Calculate number of sets for a given question count
export function getSetCount(totalQuestions: number): number {
  return Math.max(1, Math.ceil(totalQuestions / SET_SIZE));
}

// Get questions for a specific set
export function getSetQuestions<T>(questions: T[], setNum: number): T[] {
  const start = (setNum - 1) * SET_SIZE;
  return questions.slice(start, start + SET_SIZE);
}

// Navigation: get previous and next topic
export function getAdjacentTopics(topicKey: string) {
  const visible = getVisibleTopics();
  const idx = visible.findIndex(t => t.key === topicKey);
  return {
    prev: idx > 0 ? visible[idx - 1] : null,
    next: idx < visible.length - 1 ? visible[idx + 1] : null,
  };
}

// Navigation: get previous and next chapter within a topic
export function getAdjacentChapters(topic: Topic, chapterEn: string) {
  const idx = topic.chapters.findIndex(c => chapterSlug(c.en) === chapterSlug(chapterEn));
  return {
    prev: idx > 0 ? topic.chapters[idx - 1] : null,
    next: idx < topic.chapters.length - 1 ? topic.chapters[idx + 1] : null,
  };
}

// Get topics for a specific exam
export function getTopicsForExam(examId: string): { primary: Topic[], other: Topic[] } {
  const visible = getVisibleTopics();
  const primary = visible.filter(t => t.exams?.includes(examId));
  const other = visible.filter(t => !t.exams?.includes(examId));
  return { primary, other };
}
