/** @type {import('next').NextConfig} */
const nextConfig = {
  images: {
    domains: ["gkquestionsguru.com"],
  },
  async headers() {
    return [
      {
        source: "/(.*)",
        headers: [
          { key: "X-Frame-Options", value: "DENY" },
          { key: "X-Content-Type-Options", value: "nosniff" },
          { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
          { key: "X-XSS-Protection", value: "1; mode=block" },
          { key: "Permissions-Policy", value: "camera=(), microphone=(), geolocation=()" },
        ],
      },
      {
        source: "/_next/static/(.*)",
        headers: [
          { key: "Cache-Control", value: "public, max-age=31536000, immutable" },
        ],
      },
      {
        source: "/(.*)\\.(ico|png|jpg|jpeg|svg|webp|woff|woff2)",
        headers: [
          { key: "Cache-Control", value: "public, max-age=31536000, immutable" },
        ],
      },
    ];
  },
  async redirects() {
    return [
      // ── Old WordPress category pages ──
      { source: "/category/indian-history", destination: "/topics/history", permanent: true },
      { source: "/category/indian-polity", destination: "/topics/polity", permanent: true },
      { source: "/category/geography", destination: "/topics/geography", permanent: true },
      { source: "/category/economics", destination: "/topics/economics", permanent: true },
      { source: "/category/physics", destination: "/topics/physics", permanent: true },
      { source: "/category/chemistry", destination: "/topics/chemistry", permanent: true },
      { source: "/category/biology", destination: "/topics/biology", permanent: true },
      { source: "/category/sports", destination: "/topics/sports", permanent: true },
      { source: "/category/computer", destination: "/topics/computer", permanent: true },
      { source: "/category/current-affairs", destination: "/current-affairs", permanent: true },
      { source: "/category/:slug*", destination: "/topics", permanent: true },

      // ── Old WordPress static pages ──
      // NOTE: /about, /contact, /privacy-policy are now real pages — do NOT redirect them.
      { source: "/privacy-policy-:slug*", destination: "/privacy-policy", permanent: true },
      { source: "/elementor-:slug*", destination: "/", permanent: true },
      { source: "/quizzes-with-time-limit", destination: "/topics", permanent: true },
      { source: "/download-:slug*", destination: "/", permanent: true },

      // ── Old History pages → /topics/history ──
      { source: "/indian-history-in-hindi/:path*", destination: "/topics/history", permanent: true },
      { source: "/history-questions/:path*", destination: "/topics/history", permanent: true },
      { source: "/vedic-culture/:path*", destination: "/topics/history", permanent: true },
      { source: "/vedic-culture", destination: "/topics/history", permanent: true },
      { source: "/gandhi-era-:slug*", destination: "/topics/history", permanent: true },
      { source: "/mughal-period-:slug*", destination: "/topics/history", permanent: true },
      { source: "/sultanate-period-:slug*", destination: "/topics/history", permanent: true },
      { source: "/maurya-:slug*", destination: "/topics/history", permanent: true },
      { source: "/post-gupta-:slug*", destination: "/topics/history", permanent: true },
      { source: "/early-medieval-:slug*", destination: "/topics/history", permanent: true },
      { source: "/arrival-of-the-europeans/:path*", destination: "/topics/history", permanent: true },
      { source: "/maratha-state-:slug*", destination: "/topics/history", permanent: true },
      { source: "/expansion-of-british-:slug*", destination: "/topics/history", permanent: true },
      { source: "/impact-of-british-:slug*", destination: "/topics/history", permanent: true },
      { source: "/miscellaneous-modern-india/:path*", destination: "/topics/history", permanent: true },
      { source: "/constituent-assembly/:path*", destination: "/topics/polity", permanent: true },

      // ── Old Polity pages → /topics/polity ──
      { source: "/indian-polity-questions/:path*", destination: "/topics/polity", permanent: true },
      { source: "/indian-polity-in-hindi/:path*", destination: "/topics/polity", permanent: true },
      { source: "/indian-polity-2", destination: "/topics/polity", permanent: true },
      { source: "/articles-of-the-constitution/:path*", destination: "/topics/polity", permanent: true },
      { source: "/articles-of-the-constitution", destination: "/topics/polity", permanent: true },
      { source: "/constitutional-amendment/:path*", destination: "/topics/polity", permanent: true },
      { source: "/constitutional-amendment", destination: "/topics/polity", permanent: true },
      { source: "/fundamental-rights/:path*", destination: "/topics/polity", permanent: true },
      { source: "/parliamentary-committees", destination: "/topics/polity", permanent: true },
      { source: "/emergency-provisions/:path*", destination: "/topics/polity", permanent: true },
      { source: "/parts-of-the-constitution", destination: "/topics/polity", permanent: true },
      { source: "/schedules-of-the-constitution/:path*", destination: "/topics/polity", permanent: true },
      { source: "/lok-sabha/:path*", destination: "/topics/polity", permanent: true },
      { source: "/governor/:path*", destination: "/topics/polity", permanent: true },
      { source: "/president/:path*", destination: "/topics/polity", permanent: true },
      { source: "/vice-president/:path*", destination: "/topics/polity", permanent: true },
      { source: "/union-and-its-territories/:path*", destination: "/topics/polity", permanent: true },
      { source: "/assembly/:path*", destination: "/topics/polity", permanent: true },
      { source: "/key-office-bearers-:slug*", destination: "/topics/polity", permanent: true },

      // ── Old Geography pages → /topics/geography ──
      { source: "/geography/:path*", destination: "/topics/geography", permanent: true },
      { source: "/geography-in-hindi/:path*", destination: "/topics/geography", permanent: true },
      { source: "/geography-in-hindi", destination: "/topics/geography", permanent: true },
      { source: "/solar-system/:path*", destination: "/topics/geography", permanent: true },
      { source: "/rivers-of-india-:slug*", destination: "/topics/geography", permanent: true },
      { source: "/mountains-of-india/:path*", destination: "/topics/geography", permanent: true },
      { source: "/mountain-passes-of-india", destination: "/topics/geography", permanent: true },
      { source: "/composition-of-the-atmosphere/:path*", destination: "/topics/geography", permanent: true },
      { source: "/location-and-extent-of-india/:path*", destination: "/topics/geography", permanent: true },
      { source: "/agriculture-in-india/:path*", destination: "/topics/geography", permanent: true },
      { source: "/agriculture-of-india/:path*", destination: "/topics/geography", permanent: true },
      { source: "/industries-of-india/:path*", destination: "/topics/geography", permanent: true },
      { source: "/transport-and-communication/:path*", destination: "/topics/geography", permanent: true },
      { source: "/continents-of-the-world/:path*", destination: "/topics/geography", permanent: true },
      { source: "/oceans-and-seas-of-the-world/:path*", destination: "/topics/geography", permanent: true },
      { source: "/population-and-urbanization/:path*", destination: "/topics/geography", permanent: true },
      { source: "/natural-regions-of-the-world/:path*", destination: "/topics/geography", permanent: true },
      { source: "/cyclone-and-anticyclone/:path*", destination: "/topics/geography", permanent: true },
      { source: "/clouds-and-precipitation/:path*", destination: "/topics/geography", permanent: true },
      { source: "/energy-resources-of-india/:path*", destination: "/topics/geography", permanent: true },
      { source: "/world-population/:path*", destination: "/topics/geography", permanent: true },
      { source: "/world-population", destination: "/topics/geography", permanent: true },
      { source: "/world-fishing/:path*", destination: "/topics/geography", permanent: true },
      { source: "/ports-of-the-world/:path*", destination: "/topics/geography", permanent: true },
      { source: "/major-industries-of-the-world/:path*", destination: "/topics/geography", permanent: true },
      { source: "/tribes-of-the-world/:path*", destination: "/topics/geography", permanent: true },
      { source: "/lines-marked-on-maps", destination: "/topics/geography", permanent: true },
      { source: "/cities-situated-on-the-banks-of-rivers/:path*", destination: "/topics/geography", permanent: true },
      { source: "/largest-lake-in-india", destination: "/topics/geography", permanent: true },
      { source: "/caves-in-india", destination: "/topics/geography", permanent: true },
      { source: "/superlatives-of-india", destination: "/topics/geography", permanent: true },

      // ── Old Economics pages → /topics/economics ──
      { source: "/indian-economy/:path*", destination: "/topics/economics", permanent: true },
      { source: "/indian-economy-in-hindi/:path*", destination: "/topics/economics", permanent: true },
      { source: "/economic-planning-in-india/:path*", destination: "/topics/economics", permanent: true },
      { source: "/economic-committees/:path*", destination: "/topics/economics", permanent: true },
      { source: "/currency-and-banking/:path*", destination: "/topics/economics", permanent: true },
      { source: "/revenue/:path*", destination: "/topics/economics", permanent: true },
      { source: "/development/:path*", destination: "/topics/economics", permanent: true },
      { source: "/international-business/:path*", destination: "/topics/economics", permanent: true },

      // ── Old Physics pages → /topics/physics ──
      { source: "/physics/:path*", destination: "/topics/physics", permanent: true },
      { source: "/physics-in-hindi/:path*", destination: "/topics/physics", permanent: true },
      { source: "/mechanics/:path*", destination: "/topics/physics", permanent: true },
      { source: "/heat-and-temperature/:path*", destination: "/topics/physics", permanent: true },
      { source: "/light/:path*", destination: "/topics/physics", permanent: true },
      { source: "/modern-physics", destination: "/topics/physics", permanent: true },

      // ── Old Chemistry pages → /topics/chemistry ──
      { source: "/chemistry/:path*", destination: "/topics/chemistry", permanent: true },
      { source: "/chemistry-in-hindi/:path*", destination: "/topics/chemistry", permanent: true },
      { source: "/metals-and-their-compounds/:path*", destination: "/topics/chemistry", permanent: true },
      { source: "/metals-and-their-compounds", destination: "/topics/chemistry", permanent: true },
      { source: "/non-metals-and-their-compounds/:path*", destination: "/topics/chemistry", permanent: true },
      { source: "/acid-ashes-and-salts/:path*", destination: "/topics/chemistry", permanent: true },
      { source: "/organic-chemistry/:path*", destination: "/topics/chemistry", permanent: true },
      { source: "/atomic-structure/:path*", destination: "/topics/chemistry", permanent: true },
      { source: "/state-of-matter", destination: "/topics/chemistry", permanent: true },
      { source: "/general-properties-of-gases", destination: "/topics/chemistry", permanent: true },

      // ── Old Biology pages → /topics/biology ──
      { source: "/biology/:path*", destination: "/topics/biology", permanent: true },
      { source: "/biology-in-hindi/:path*", destination: "/topics/biology", permanent: true },
      { source: "/human-physiology/:path*", destination: "/topics/biology", permanent: true },
      { source: "/classification-of-animalia/:path*", destination: "/topics/biology", permanent: true },
      { source: "/plant-morphology/:path*", destination: "/topics/biology", permanent: true },
      { source: "/plant-physiology/:path*", destination: "/topics/biology", permanent: true },
      { source: "/taxonomy-of-covered-seeds/:path*", destination: "/topics/biology", permanent: true },
      { source: "/health-and-nutrition/:path*", destination: "/topics/biology", permanent: true },

      // ── Old Computer pages → /topics/computer ──
      { source: "/computer-basics/:path*", destination: "/topics/computer", permanent: true },
      { source: "/computer-awareness-:slug*", destination: "/topics/computer", permanent: true },
      { source: "/operating-system/:path*", destination: "/topics/computer", permanent: true },

      // ── Old GK / Culture pages → relevant topics ──
      { source: "/basic-general-knowledge/:path*", destination: "/topics", permanent: true },
      { source: "/folk-art-style-and-folk-dance/:path*", destination: "/topics/arts", permanent: true },
      { source: "/gharanas-and-styles-of-classical-music/:path*", destination: "/topics/arts", permanent: true },
      { source: "/famous-personalities/:path*", destination: "/topics/famous-people", permanent: true },
      { source: "/inventions/:path*", destination: "/topics/inventions", permanent: true },
      { source: "/inventions", destination: "/topics/inventions", permanent: true },
      { source: "/sports-glossaries/:path*", destination: "/topics/sports", permanent: true },
      { source: "/sports-glossaries", destination: "/topics/sports", permanent: true },
      { source: "/players-and-related-sports/:path*", destination: "/topics/sports", permanent: true },
      { source: "/days-and-years-in-hindi/:path*", destination: "/topics/days-years", permanent: true },
      { source: "/famous-places-in-india-in-hindi/:path*", destination: "/topics/famous-places", permanent: true },
      { source: "/famous-places-in-india-in-hindi", destination: "/topics/famous-places", permanent: true },
      { source: "/famous-historical-:slug*", destination: "/topics/famous-places", permanent: true },
      { source: "/languages-of-india/:path*", destination: "/topics/arts", permanent: true },
      { source: "/major-religions-of-the-world/:path*", destination: "/topics/arts", permanent: true },
      { source: "/geographical-texts-:slug*", destination: "/topics/geography", permanent: true },

      // ── Old State GK pages → relevant state topics ──
      { source: "/assam/:path*", destination: "/topics", permanent: true },
      { source: "/assam", destination: "/topics", permanent: true },
      { source: "/gujarat/:path*", destination: "/topics/gujarat-gk", permanent: true },
      { source: "/gujarat", destination: "/topics/gujarat-gk", permanent: true },
      { source: "/haryana/:path*", destination: "/topics/haryana-gk", permanent: true },
      { source: "/haryana", destination: "/topics/haryana-gk", permanent: true },
      { source: "/punjab/:path*", destination: "/topics", permanent: true },
      { source: "/madhya-pradesh/:path*", destination: "/topics/mp-gk", permanent: true },
      { source: "/sikkim/:path*", destination: "/topics", permanent: true },
      { source: "/tamil-nadu/:path*", destination: "/topics", permanent: true },
      { source: "/tripura/:path*", destination: "/topics", permanent: true },
      { source: "/uttar-pradesh/:path*", destination: "/topics/up-gk", permanent: true },
      { source: "/west-bengal/:path*", destination: "/topics", permanent: true },
      { source: "/west-bengal", destination: "/topics", permanent: true },

      // ── Old Railway PYQ pages → /pyq/rrb-ntpc ──
      { source: "/railway-ntpc-and-railway-group-d-:slug*", destination: "/pyq/rrb-ntpc", permanent: true },
      { source: "/set-:n(\\d+)-indian-history-:lang(hindi|english)-railway-:slug*", destination: "/pyq/rrb-ntpc", permanent: true },
      { source: "/set-:n(\\d+)-indian-geography-:lang(hindi|english)-railway-:slug*", destination: "/pyq/rrb-ntpc", permanent: true },
      { source: "/set-:n(\\d+)-indian-polity-:lang(hindi|english)-railway-:slug*", destination: "/pyq/rrb-ntpc", permanent: true },
      { source: "/set-:n(\\d+)-indian-economics-:lang(hindi|english)-railway-:slug*", destination: "/pyq/rrb-ntpc", permanent: true },
      { source: "/set-:n(\\d+)-general-science-:lang(hindi|english)-railway-:slug*", destination: "/pyq/rrb-ntpc", permanent: true },
      { source: "/set-:n(\\d+)-railway-ntpc-:slug*", destination: "/pyq/rrb-ntpc", permanent: true },
      { source: "/160rrb-ntpc-:slug*", destination: "/pyq/rrb-ntpc", permanent: true },

      // ── Old SSC pages → /pyq/ssc-cgl ──
      { source: "/ssc-chsl-previous-year-:slug*", destination: "/pyq/ssc-chsl", permanent: true },
      { source: "/ssc-chsl-previous-year-:slug*/:path*", destination: "/pyq/ssc-chsl", permanent: true },
      { source: "/ssc-cpo-previous-year-:slug*/:path*", destination: "/pyq/ssc-cpo", permanent: true },
      { source: "/ssc-cpo-previous-year-:slug*", destination: "/pyq/ssc-cpo", permanent: true },
      { source: "/classification-questions-for-ssc-:slug*", destination: "/pyq/ssc-cgl", permanent: true },

      // ── Old Banking/SBI quiz pages → homepage ──
      { source: "/sbi-clerk-:slug*", destination: "/", permanent: true },
      { source: "/sbi-po-:slug*", destination: "/", permanent: true },
      { source: "/ibps-clerk-:slug*", destination: "/", permanent: true },
      { source: "/ibps-po-:slug*", destination: "/", permanent: true },
      { source: "/banking-and-financial-:slug*", destination: "/topics/banking", permanent: true },
      { source: "/static-awareness/:path*", destination: "/topics", permanent: true },

      // ── Old English pages → /english ──
      { source: "/spot-the-error-:slug*", destination: "/english", permanent: true },
      { source: "/spot-error-:slug*", destination: "/english", permanent: true },
      { source: "/reading-comprehension-:slug*", destination: "/english", permanent: true },
      { source: "/cloze-test-:slug*", destination: "/english", permanent: true },
      { source: "/fill-in-the-blanks-:slug*", destination: "/english", permanent: true },
      { source: "/fill-blanks-:slug*", destination: "/english", permanent: true },
      { source: "/para-jumbles-:slug*", destination: "/english", permanent: true },
      { source: "/para-jumbles/:path*", destination: "/english", permanent: true },
      { source: "/one-word-substitution/:path*", destination: "/english", permanent: true },
      { source: "/idioms-and-phrases/:path*", destination: "/english", permanent: true },
      { source: "/synonyms-meaning-in-hindi/:path*", destination: "/english", permanent: true },
      { source: "/antonyms-meaning-in-hindi/:path*", destination: "/english", permanent: true },
      { source: "/antonyms-meaning-in-hindi", destination: "/english", permanent: true },
      { source: "/spelling-check/:path*", destination: "/english", permanent: true },
      { source: "/spelling-check", destination: "/english", permanent: true },
      { source: "/article-questions/:path*", destination: "/english", permanent: true },
      { source: "/active-and-passive-voice-:slug*", destination: "/english", permanent: true },
      { source: "/direct-and-indirect-speech-:slug*", destination: "/english", permanent: true },
      { source: "/preposition-exercises-:slug*", destination: "/english", permanent: true },
      { source: "/selecting-words/:path*", destination: "/english", permanent: true },
      { source: "/completing-statements/:path*", destination: "/english", permanent: true },
      { source: "/complete-the-phrase/:path*", destination: "/english", permanent: true },
      { source: "/phrase-replacement-:slug*", destination: "/english", permanent: true },
      { source: "/coding-decoding-:slug*", destination: "/english", permanent: true },
      { source: "/verbal-analogies/:path*", destination: "/english", permanent: true },

      // ── Old Reasoning pages → homepage ──
      { source: "/reasoning-:slug*", destination: "/", permanent: true },
      { source: "/syllogism-:slug*", destination: "/", permanent: true },
      { source: "/inequality-reasoning-:slug*", destination: "/", permanent: true },
      { source: "/inequalities-:slug*", destination: "/", permanent: true },
      { source: "/alphanumeric-:slug*", destination: "/", permanent: true },
      { source: "/floor-puzzle-:slug*", destination: "/", permanent: true },
      { source: "/month-puzzle-:slug*", destination: "/", permanent: true },
      { source: "/box-puzzle-:slug*", destination: "/", permanent: true },
      { source: "/puzzle-:slug*", destination: "/", permanent: true },
      { source: "/circular-sitting-:slug*", destination: "/", permanent: true },
      { source: "/day-calendar-:slug*", destination: "/", permanent: true },
      { source: "/statement-:slug*", destination: "/", permanent: true },
      { source: "/artificial-language-:slug*", destination: "/", permanent: true },
      { source: "/continuous-pattern-:slug*", destination: "/", permanent: true },
      { source: "/coding-decoding-questions/:path*", destination: "/", permanent: true },

      // ── Old Maths pages → homepage ──
      { source: "/simplification-:slug*", destination: "/", permanent: true },
      { source: "/simplification/:path*", destination: "/", permanent: true },
      { source: "/simplification", destination: "/", permanent: true },
      { source: "/quadratic-equation:slug*", destination: "/", permanent: true },
      { source: "/number-series-:slug*", destination: "/", permanent: true },
      { source: "/arithmetic-:slug*", destination: "/", permanent: true },
      { source: "/data-interpretation-:slug*", destination: "/", permanent: true },
      { source: "/data-interpretation/:path*", destination: "/", permanent: true },
      { source: "/data-interpretation", destination: "/", permanent: true },
      { source: "/profit-and-loss-:slug*", destination: "/", permanent: true },
      { source: "/partnership-questions/:path*", destination: "/", permanent: true },
      { source: "/partnership-questions", destination: "/", permanent: true },
      { source: "/percentage-questions/:path*", destination: "/", permanent: true },
      { source: "/speed-distance-:slug*", destination: "/", permanent: true },
      { source: "/boat-and-stream-:slug*", destination: "/", permanent: true },
      { source: "/pipe-and-cistern-:slug*", destination: "/", permanent: true },
      { source: "/problems-on-ages-:slug*", destination: "/", permanent: true },
      { source: "/time-and-work-:slug*", destination: "/", permanent: true },
      { source: "/simple-interest-:slug*", destination: "/", permanent: true },
      { source: "/average-questions/:path*", destination: "/", permanent: true },
      { source: "/average-questions", destination: "/", permanent: true },
      { source: "/ratio-and-proportion-:slug*", destination: "/", permanent: true },
      { source: "/mixture-alligation-:slug*", destination: "/", permanent: true },
      { source: "/top-25-percentage-:slug*", destination: "/", permanent: true },

      // ── Old Current Affairs pages → /current-affairs ──
      { source: "/vision-ias-current-affairs:slug*", destination: "/current-affairs", permanent: true },
      { source: "/current-affairs-quiz-:slug*", destination: "/current-affairs", permanent: true },
      { source: "/may-monthly-current-affairs/:path*", destination: "/current-affairs", permanent: true },
      { source: "/may-monthly-current-affairs", destination: "/current-affairs", permanent: true },
      { source: "/march-monthly-current-affairs/:path*", destination: "/current-affairs", permanent: true },
      { source: "/april-monthly-current-affairs/:path*", destination: "/current-affairs", permanent: true },
      { source: "/august-current-affairs-:slug*", destination: "/current-affairs", permanent: true },
      { source: "/october-current-affairs-:slug*", destination: "/current-affairs", permanent: true },
      { source: "/december-current-affairs-:slug*", destination: "/current-affairs", permanent: true },
      { source: "/november-current-affairs-:slug*", destination: "/current-affairs", permanent: true },
      { source: "/september-current-affairs-:slug*", destination: "/current-affairs", permanent: true },
      { source: "/july-current-affairs-:slug*", destination: "/current-affairs", permanent: true },
      { source: "/december-2022/:path*", destination: "/current-affairs", permanent: true },
      { source: "/:n(\\d+)th-:slug*-current-affairs:path*", destination: "/current-affairs", permanent: true },
      { source: "/:n(\\d+)st-:slug*-current-affairs:path*", destination: "/current-affairs", permanent: true },
      { source: "/:n(\\d+)nd-:slug*-current-affairs:path*", destination: "/current-affairs", permanent: true },
      { source: "/:n(\\d+)rd-:slug*-current-affairs:path*", destination: "/current-affairs", permanent: true },

      // ── Old Misc / Blog pages → homepage ──
      { source: "/best-gk-trick:slug*", destination: "/topics", permanent: true },
      { source: "/best-trick-:slug*", destination: "/topics", permanent: true },
      { source: "/how-to-memorize-:slug*", destination: "/topics", permanent: true },
      { source: "/list-of-:slug*", destination: "/topics", permanent: true },
      { source: "/top-10-:slug*", destination: "/", permanent: true },
      { source: "/3-awesome-:slug*", destination: "/", permanent: true },
      { source: "/quiz-ibps-clerk", destination: "/", permanent: true },
      { source: "/radio-and-television", destination: "/topics", permanent: true },
      { source: "/analyzing-arguments", destination: "/", permanent: true },
      { source: "/miscellaneous/:path*", destination: "/topics", permanent: true },
      { source: "/money-market", destination: "/topics/economics", permanent: true },

      // ── Old Teaching/Research pages ──
      { source: "/teaching-and-research-in-hindi/:path*", destination: "/topics", permanent: true },
      { source: "/teaching-and-research-in-hindi", destination: "/topics", permanent: true },
      { source: "/teaching-and-research/:path*", destination: "/topics", permanent: true },

      // ── Old date-format posts ──
      { source: "/:year(\\d{4})/:month(\\d{2})/:day(\\d{2})/:slug*", destination: "/", permanent: true },

      // ── Attachment/RSS pages ──
      { source: "/:path*attachment_id:slug*", destination: "/", permanent: true },

      // ── Old set-based quiz pages (SBI/banking) → homepage ──
      { source: "/set-:n(\\d+)-:slug*-for-sbi-:path*", destination: "/", permanent: true },
      { source: "/quiz-:n(\\d+)-:slug*-for-sbi-:path*", destination: "/", permanent: true },

      // ── Old number IDs ──
      { source: "/32329-2", destination: "/", permanent: true },
      { source: "/32352-2", destination: "/", permanent: true },
      { source: "/32311-2", destination: "/", permanent: true },
      { source: "/25th-february-:slug*", destination: "/", permanent: true },

      // ── Catch-all: any old paginated URL with /number at end ──
      { source: "/profit-and-loss-:slug*", destination: "/", permanent: true },
      { source: "/syllogism-questions/:path*", destination: "/", permanent: true },
      { source: "/indian-polity-in-hindi/:path*", destination: "/topics/polity", permanent: true },
      { source: "/indian-railway-in-hindi/:path*", destination: "/topics/railways", permanent: true },
      { source: "/ssc-chsl-previous-year-gk-questions/:path*", destination: "/pyq/ssc-chsl", permanent: true },
      { source: "/ssc-cpo-previous-year-gk-questions/:path*", destination: "/pyq/ssc-cpo", permanent: true },
      { source: "/spot-the-error/:path*", destination: "/english", permanent: true },
      { source: "/one-word-substitution/:path*", destination: "/english", permanent: true },
      { source: "/para-jumbles-for-all-competitive-exams/:path*", destination: "/english", permanent: true },
      { source: "/cloze-test-questions/:path*", destination: "/english", permanent: true },
      { source: "/reading-comprehension-for-bank-exams/:path*", destination: "/english", permanent: true },
      { source: "/direct-and-indirect-speech-exercises/:path*", destination: "/english", permanent: true },
      { source: "/preposition-exercises-with-answers/:path*", destination: "/english", permanent: true },
      { source: "/data-interpretation-questions/:path*", destination: "/", permanent: true },
      { source: "/quadratic-equation-for-bank-exam/:path*", destination: "/", permanent: true },
      { source: "/arithmetic-questions-and-answers/:path*", destination: "/", permanent: true },
      { source: "/boat-and-stream-questions/:path*", destination: "/", permanent: true },
      { source: "/simplification-questions/:path*", destination: "/", permanent: true },
    ];
  },
};

export default nextConfig;
